// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: learningagent/learning_agent.proto

package learningagentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LearningAgent_Exchange_FullMethodName = "/pbft.learningagent.v1.LearningAgent/Exchange"
)

// LearningAgentClient is the client API for LearningAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LearningAgentClient interface {
	Exchange(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
}

type learningAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewLearningAgentClient(cc grpc.ClientConnInterface) LearningAgentClient {
	return &learningAgentClient{cc}
}

func (c *learningAgentClient) Exchange(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, LearningAgent_Exchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LearningAgentServer is the server API for LearningAgent service.
// All implementations must embed UnimplementedLearningAgentServer
// for forward compatibility.
type LearningAgentServer interface {
	Exchange(context.Context, *NodeRequest) (*NodeResponse, error)
	mustEmbedUnimplementedLearningAgentServer()
}

// UnimplementedLearningAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLearningAgentServer struct{}

func (UnimplementedLearningAgentServer) Exchange(context.Context, *NodeRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exchange not implemented")
}
func (UnimplementedLearningAgentServer) mustEmbedUnimplementedLearningAgentServer() {}
func (UnimplementedLearningAgentServer) testEmbeddedByValue()                       {}

// UnsafeLearningAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LearningAgentServer will
// result in compilation errors.
type UnsafeLearningAgentServer interface {
	mustEmbedUnimplementedLearningAgentServer()
}

func RegisterLearningAgentServer(s grpc.ServiceRegistrar, srv LearningAgentServer) {
	// If the following call panics, it indicates UnimplementedLearningAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LearningAgent_ServiceDesc, srv)
}

func _LearningAgent_Exchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningAgentServer).Exchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearningAgent_Exchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningAgentServer).Exchange(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LearningAgent_ServiceDesc is the grpc.ServiceDesc for LearningAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LearningAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbft.learningagent.v1.LearningAgent",
	HandlerType: (*LearningAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exchange",
			Handler:    _LearningAgent_Exchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "learningagent/learning_agent.proto",
}
