// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: learningagent/learning_agent.proto

package learningagentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRequest) Reset() {
	*x = NodeRequest{}
	mi := &file_learningagent_learning_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRequest) ProtoMessage() {}

func (x *NodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learningagent_learning_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRequest.ProtoReflect.Descriptor instead.
func (*NodeRequest) Descriptor() ([]byte, []int) {
	return file_learningagent_learning_agent_proto_rawDescGZIP(), []int{0}
}

func (x *NodeRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type NodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResponse) Reset() {
	*x = NodeResponse{}
	mi := &file_learningagent_learning_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResponse) ProtoMessage() {}

func (x *NodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learningagent_learning_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResponse.ProtoReflect.Descriptor instead.
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return file_learningagent_learning_agent_proto_rawDescGZIP(), []int{1}
}

func (x *NodeResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_learningagent_learning_agent_proto protoreflect.FileDescriptor

const file_learningagent_learning_agent_proto_rawDesc = "" +
	"\n" +
	"\"learningagent/learning_agent.proto\x12\x15pbft.learningagent.v1\"@\n" +
	"\vNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"A\n" +
	"\fNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload2d\n" +
	"\rLearningAgent\x12S\n" +
	"\bExchange\x12\".pbft.learningagent.v1.NodeRequest\x1a#.pbft.learningagent.v1.NodeResponseB?Z=github.com/michael112233/pbft/learningagentpb;learningagentpbb\x06proto3"

var (
	file_learningagent_learning_agent_proto_rawDescOnce sync.Once
	file_learningagent_learning_agent_proto_rawDescData []byte
)

func file_learningagent_learning_agent_proto_rawDescGZIP() []byte {
	file_learningagent_learning_agent_proto_rawDescOnce.Do(func() {
		file_learningagent_learning_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learningagent_learning_agent_proto_rawDesc), len(file_learningagent_learning_agent_proto_rawDesc)))
	})
	return file_learningagent_learning_agent_proto_rawDescData
}

var file_learningagent_learning_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_learningagent_learning_agent_proto_goTypes = []any{
	(*NodeRequest)(nil),  // 0: pbft.learningagent.v1.NodeRequest
	(*NodeResponse)(nil), // 1: pbft.learningagent.v1.NodeResponse
}
var file_learningagent_learning_agent_proto_depIdxs = []int32{
	0, // 0: pbft.learningagent.v1.LearningAgent.Exchange:input_type -> pbft.learningagent.v1.NodeRequest
	1, // 1: pbft.learningagent.v1.LearningAgent.Exchange:output_type -> pbft.learningagent.v1.NodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_learningagent_learning_agent_proto_init() }
func file_learningagent_learning_agent_proto_init() {
	if File_learningagent_learning_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learningagent_learning_agent_proto_rawDesc), len(file_learningagent_learning_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_learningagent_learning_agent_proto_goTypes,
		DependencyIndexes: file_learningagent_learning_agent_proto_depIdxs,
		MessageInfos:      file_learningagent_learning_agent_proto_msgTypes,
	}.Build()
	File_learningagent_learning_agent_proto = out.File
	file_learningagent_learning_agent_proto_goTypes = nil
	file_learningagent_learning_agent_proto_depIdxs = nil
}
