# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: learningagent/learning_agent.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'learningagent/learning_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"learningagent/learning_agent.proto\x12\x15pbft.learningagent.v1\"/\n\x0bNodeRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"0\n\x0cNodeResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x32\x64\n\rLearningAgent\x12S\n\x08\x45xchange\x12\".pbft.learningagent.v1.NodeRequest\x1a#.pbft.learningagent.v1.NodeResponseB?Z=github.com/michael112233/pbft/learningagentpb;learningagentpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'learningagent.learning_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/michael112233/pbft/learningagentpb;learningagentpb'
  _globals['_NODEREQUEST']._serialized_start=61
  _globals['_NODEREQUEST']._serialized_end=108
  _globals['_NODERESPONSE']._serialized_start=110
  _globals['_NODERESPONSE']._serialized_end=158
  _globals['_LEARNINGAGENT']._serialized_start=160
  _globals['_LEARNINGAGENT']._serialized_end=260
# @@protoc_insertion_point(module_scope)
