// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pbft_transport.proto

package transportpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_pbft_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Transaction) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ClientMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Txn           *Transaction           `protobuf:"bytes,3,opt,name=txn,proto3" json:"txn,omitempty"`
	ClientName    string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMsg) Reset() {
	*x = ClientMsg{}
	mi := &file_pbft_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMsg) ProtoMessage() {}

func (x *ClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMsg.ProtoReflect.Descriptor instead.
func (*ClientMsg) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMsg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClientMsg) GetTxn() *Transaction {
	if x != nil {
		return x.Txn
	}
	return nil
}

func (x *ClientMsg) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

type ClientMsgSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ClientMsg             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMsgSignature) Reset() {
	*x = ClientMsgSignature{}
	mi := &file_pbft_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMsgSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMsgSignature) ProtoMessage() {}

func (x *ClientMsgSignature) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMsgSignature.ProtoReflect.Descriptor instead.
func (*ClientMsgSignature) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{2}
}

func (x *ClientMsgSignature) GetData() *ClientMsg {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClientMsgSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []*ClientMsgSignature  `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	mi := &file_pbft_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{3}
}

func (x *RequestMessage) GetTxs() []*ClientMsgSignature {
	if x != nil {
		return x.Txs
	}
	return nil
}

type PreprepareMsg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	View            int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum          int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	ClientMsg       *ClientMsgSignature    `protobuf:"bytes,3,opt,name=client_msg,json=clientMsg,proto3" json:"client_msg,omitempty"`
	To              string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	DigestClientMsg []byte                 `protobuf:"bytes,5,opt,name=digest_client_msg,json=digestClientMsg,proto3" json:"digest_client_msg,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreprepareMsg) Reset() {
	*x = PreprepareMsg{}
	mi := &file_pbft_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprepareMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprepareMsg) ProtoMessage() {}

func (x *PreprepareMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprepareMsg.ProtoReflect.Descriptor instead.
func (*PreprepareMsg) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{4}
}

func (x *PreprepareMsg) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PreprepareMsg) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PreprepareMsg) GetClientMsg() *ClientMsgSignature {
	if x != nil {
		return x.ClientMsg
	}
	return nil
}

func (x *PreprepareMsg) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *PreprepareMsg) GetDigestClientMsg() []byte {
	if x != nil {
		return x.DigestClientMsg
	}
	return nil
}

type PreprepareSignPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	View            int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum          int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	DigestClientMsg []byte                 `protobuf:"bytes,3,opt,name=digest_client_msg,json=digestClientMsg,proto3" json:"digest_client_msg,omitempty"`
	To              string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreprepareSignPayload) Reset() {
	*x = PreprepareSignPayload{}
	mi := &file_pbft_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprepareSignPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprepareSignPayload) ProtoMessage() {}

func (x *PreprepareSignPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprepareSignPayload.ProtoReflect.Descriptor instead.
func (*PreprepareSignPayload) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{5}
}

func (x *PreprepareSignPayload) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PreprepareSignPayload) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PreprepareSignPayload) GetDigestClientMsg() []byte {
	if x != nil {
		return x.DigestClientMsg
	}
	return nil
}

func (x *PreprepareSignPayload) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type PrepareMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum        int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	From          int32                  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMsg) Reset() {
	*x = PrepareMsg{}
	mi := &file_pbft_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMsg) ProtoMessage() {}

func (x *PrepareMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMsg.ProtoReflect.Descriptor instead.
func (*PrepareMsg) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{6}
}

func (x *PrepareMsg) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PrepareMsg) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PrepareMsg) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PrepareMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *PrepareMsg) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type CommitMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum        int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	From          int32                  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMsg) Reset() {
	*x = CommitMsg{}
	mi := &file_pbft_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMsg) ProtoMessage() {}

func (x *CommitMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMsg.ProtoReflect.Descriptor instead.
func (*CommitMsg) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{7}
}

func (x *CommitMsg) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *CommitMsg) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *CommitMsg) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CommitMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *CommitMsg) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ReplyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	ClientMsg     *ClientMsg             `protobuf:"bytes,3,opt,name=client_msg,json=clientMsg,proto3" json:"client_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	mi := &file_pbft_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{8}
}

func (x *ReplyMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ReplyMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ReplyMessage) GetClientMsg() *ClientMsg {
	if x != nil {
		return x.ClientMsg
	}
	return nil
}

type CloseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseMessage) Reset() {
	*x = CloseMessage{}
	mi := &file_pbft_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseMessage) ProtoMessage() {}

func (x *CloseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseMessage.ProtoReflect.Descriptor instead.
func (*CloseMessage) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{9}
}

func (x *CloseMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CloseMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CloseMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MsgType   string                 `protobuf:"bytes,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	From      int32                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	Signature []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Request
	//	*Envelope_Preprepare
	//	*Envelope_Prepare
	//	*Envelope_Commit
	//	*Envelope_Reply
	//	*Envelope_Close
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_pbft_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{10}
}

func (x *Envelope) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *Envelope) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetRequest() *RequestMessage {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Envelope) GetPreprepare() *PreprepareMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Preprepare); ok {
			return x.Preprepare
		}
	}
	return nil
}

func (x *Envelope) GetPrepare() *PrepareMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Prepare); ok {
			return x.Prepare
		}
	}
	return nil
}

func (x *Envelope) GetCommit() *CommitMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *Envelope) GetReply() *ReplyMessage {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Reply); ok {
			return x.Reply
		}
	}
	return nil
}

func (x *Envelope) GetClose() *CloseMessage {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Request struct {
	Request *RequestMessage `protobuf:"bytes,10,opt,name=request,proto3,oneof"`
}

type Envelope_Preprepare struct {
	Preprepare *PreprepareMsg `protobuf:"bytes,11,opt,name=preprepare,proto3,oneof"`
}

type Envelope_Prepare struct {
	Prepare *PrepareMsg `protobuf:"bytes,12,opt,name=prepare,proto3,oneof"`
}

type Envelope_Commit struct {
	Commit *CommitMsg `protobuf:"bytes,13,opt,name=commit,proto3,oneof"`
}

type Envelope_Reply struct {
	Reply *ReplyMessage `protobuf:"bytes,14,opt,name=reply,proto3,oneof"`
}

type Envelope_Close struct {
	Close *CloseMessage `protobuf:"bytes,15,opt,name=close,proto3,oneof"`
}

func (*Envelope_Request) isEnvelope_Body() {}

func (*Envelope_Preprepare) isEnvelope_Body() {}

func (*Envelope_Prepare) isEnvelope_Body() {}

func (*Envelope_Commit) isEnvelope_Body() {}

func (*Envelope_Reply) isEnvelope_Body() {}

func (*Envelope_Close) isEnvelope_Body() {}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pbft_transport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{11}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pbft_transport_proto protoreflect.FileDescriptor

const file_pbft_transport_proto_rawDesc = "" +
	"\n" +
	"\x14pbft_transport.proto\x12\x11pbft.transport.v1\"w\n" +
	"\vTransaction\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x8c\x01\n" +
	"\tClientMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x120\n" +
	"\x03txn\x18\x03 \x01(\v2\x1e.pbft.transport.v1.TransactionR\x03txn\x12\x1f\n" +
	"\vclient_name\x18\x04 \x01(\tR\n" +
	"clientName\"d\n" +
	"\x12ClientMsgSignature\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.pbft.transport.v1.ClientMsgR\x04data\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"I\n" +
	"\x0eRequestMessage\x127\n" +
	"\x03txs\x18\x01 \x03(\v2%.pbft.transport.v1.ClientMsgSignatureR\x03txs\"\xbe\x01\n" +
	"\rPreprepareMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12D\n" +
	"\n" +
	"client_msg\x18\x03 \x01(\v2%.pbft.transport.v1.ClientMsgSignatureR\tclientMsg\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12*\n" +
	"\x11digest_client_msg\x18\x05 \x01(\fR\x0fdigestClientMsg\"\x80\x01\n" +
	"\x15PreprepareSignPayload\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12*\n" +
	"\x11digest_client_msg\x18\x03 \x01(\fR\x0fdigestClientMsg\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\"u\n" +
	"\n" +
	"PrepareMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x12\n" +
	"\x04from\x18\x04 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\"t\n" +
	"\tCommitMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x12\n" +
	"\x04from\x18\x04 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\"o\n" +
	"\fReplyMessage\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12;\n" +
	"\n" +
	"client_msg\x18\x03 \x01(\v2\x1c.pbft.transport.v1.ClientMsgR\tclientMsg\"P\n" +
	"\fCloseMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"\xc7\x03\n" +
	"\bEnvelope\x12\x19\n" +
	"\bmsg_type\x18\x01 \x01(\tR\amsgType\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x05R\x04from\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12=\n" +
	"\arequest\x18\n" +
	" \x01(\v2!.pbft.transport.v1.RequestMessageH\x00R\arequest\x12B\n" +
	"\n" +
	"preprepare\x18\v \x01(\v2 .pbft.transport.v1.PreprepareMsgH\x00R\n" +
	"preprepare\x129\n" +
	"\aprepare\x18\f \x01(\v2\x1d.pbft.transport.v1.PrepareMsgH\x00R\aprepare\x126\n" +
	"\x06commit\x18\r \x01(\v2\x1c.pbft.transport.v1.CommitMsgH\x00R\x06commit\x127\n" +
	"\x05reply\x18\x0e \x01(\v2\x1f.pbft.transport.v1.ReplyMessageH\x00R\x05reply\x127\n" +
	"\x05close\x18\x0f \x01(\v2\x1f.pbft.transport.v1.CloseMessageH\x00R\x05closeB\x06\n" +
	"\x04body\"+\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xa2\x01\n" +
	"\rPBFTTransport\x12>\n" +
	"\aDeliver\x12\x1b.pbft.transport.v1.Envelope\x1a\x16.pbft.transport.v1.Ack\x12Q\n" +
	"\x11ClientNodeChannel\x12\x1b.pbft.transport.v1.Envelope\x1a\x1b.pbft.transport.v1.Envelope(\x010\x01B7Z5github.com/michael112233/pbft/transportpb;transportpbb\x06proto3"

var (
	file_pbft_transport_proto_rawDescOnce sync.Once
	file_pbft_transport_proto_rawDescData []byte
)

func file_pbft_transport_proto_rawDescGZIP() []byte {
	file_pbft_transport_proto_rawDescOnce.Do(func() {
		file_pbft_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbft_transport_proto_rawDesc), len(file_pbft_transport_proto_rawDesc)))
	})
	return file_pbft_transport_proto_rawDescData
}

var file_pbft_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pbft_transport_proto_goTypes = []any{
	(*Transaction)(nil),           // 0: pbft.transport.v1.Transaction
	(*ClientMsg)(nil),             // 1: pbft.transport.v1.ClientMsg
	(*ClientMsgSignature)(nil),    // 2: pbft.transport.v1.ClientMsgSignature
	(*RequestMessage)(nil),        // 3: pbft.transport.v1.RequestMessage
	(*PreprepareMsg)(nil),         // 4: pbft.transport.v1.PreprepareMsg
	(*PreprepareSignPayload)(nil), // 5: pbft.transport.v1.PreprepareSignPayload
	(*PrepareMsg)(nil),            // 6: pbft.transport.v1.PrepareMsg
	(*CommitMsg)(nil),             // 7: pbft.transport.v1.CommitMsg
	(*ReplyMessage)(nil),          // 8: pbft.transport.v1.ReplyMessage
	(*CloseMessage)(nil),          // 9: pbft.transport.v1.CloseMessage
	(*Envelope)(nil),              // 10: pbft.transport.v1.Envelope
	(*Ack)(nil),                   // 11: pbft.transport.v1.Ack
}
var file_pbft_transport_proto_depIdxs = []int32{
	0,  // 0: pbft.transport.v1.ClientMsg.txn:type_name -> pbft.transport.v1.Transaction
	1,  // 1: pbft.transport.v1.ClientMsgSignature.data:type_name -> pbft.transport.v1.ClientMsg
	2,  // 2: pbft.transport.v1.RequestMessage.txs:type_name -> pbft.transport.v1.ClientMsgSignature
	2,  // 3: pbft.transport.v1.PreprepareMsg.client_msg:type_name -> pbft.transport.v1.ClientMsgSignature
	1,  // 4: pbft.transport.v1.ReplyMessage.client_msg:type_name -> pbft.transport.v1.ClientMsg
	3,  // 5: pbft.transport.v1.Envelope.request:type_name -> pbft.transport.v1.RequestMessage
	4,  // 6: pbft.transport.v1.Envelope.preprepare:type_name -> pbft.transport.v1.PreprepareMsg
	6,  // 7: pbft.transport.v1.Envelope.prepare:type_name -> pbft.transport.v1.PrepareMsg
	7,  // 8: pbft.transport.v1.Envelope.commit:type_name -> pbft.transport.v1.CommitMsg
	8,  // 9: pbft.transport.v1.Envelope.reply:type_name -> pbft.transport.v1.ReplyMessage
	9,  // 10: pbft.transport.v1.Envelope.close:type_name -> pbft.transport.v1.CloseMessage
	10, // 11: pbft.transport.v1.PBFTTransport.Deliver:input_type -> pbft.transport.v1.Envelope
	10, // 12: pbft.transport.v1.PBFTTransport.ClientNodeChannel:input_type -> pbft.transport.v1.Envelope
	11, // 13: pbft.transport.v1.PBFTTransport.Deliver:output_type -> pbft.transport.v1.Ack
	10, // 14: pbft.transport.v1.PBFTTransport.ClientNodeChannel:output_type -> pbft.transport.v1.Envelope
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pbft_transport_proto_init() }
func file_pbft_transport_proto_init() {
	if File_pbft_transport_proto != nil {
		return
	}
	file_pbft_transport_proto_msgTypes[10].OneofWrappers = []any{
		(*Envelope_Request)(nil),
		(*Envelope_Preprepare)(nil),
		(*Envelope_Prepare)(nil),
		(*Envelope_Commit)(nil),
		(*Envelope_Reply)(nil),
		(*Envelope_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbft_transport_proto_rawDesc), len(file_pbft_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pbft_transport_proto_goTypes,
		DependencyIndexes: file_pbft_transport_proto_depIdxs,
		MessageInfos:      file_pbft_transport_proto_msgTypes,
	}.Build()
	File_pbft_transport_proto = out.File
	file_pbft_transport_proto_goTypes = nil
	file_pbft_transport_proto_depIdxs = nil
}
