// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/pbft_transport.proto

package transportpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewChangeMsg_VCType int32

const (
	ViewChangeMsg_VC_TYPE_UNSPECIFIED ViewChangeMsg_VCType = 0
	ViewChangeMsg_VC_TYPE_ELECTION    ViewChangeMsg_VCType = 1
	ViewChangeMsg_VC_TYPE_ROUND_ROBIN ViewChangeMsg_VCType = 2
	ViewChangeMsg_VC_TYPE_WRR         ViewChangeMsg_VCType = 3
)

// Enum value maps for ViewChangeMsg_VCType.
var (
	ViewChangeMsg_VCType_name = map[int32]string{
		0: "VC_TYPE_UNSPECIFIED",
		1: "VC_TYPE_ELECTION",
		2: "VC_TYPE_ROUND_ROBIN",
		3: "VC_TYPE_WRR",
	}
	ViewChangeMsg_VCType_value = map[string]int32{
		"VC_TYPE_UNSPECIFIED": 0,
		"VC_TYPE_ELECTION":    1,
		"VC_TYPE_ROUND_ROBIN": 2,
		"VC_TYPE_WRR":         3,
	}
)

func (x ViewChangeMsg_VCType) Enum() *ViewChangeMsg_VCType {
	p := new(ViewChangeMsg_VCType)
	*p = x
	return p
}

func (x ViewChangeMsg_VCType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViewChangeMsg_VCType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_pbft_transport_proto_enumTypes[0].Descriptor()
}

func (ViewChangeMsg_VCType) Type() protoreflect.EnumType {
	return &file_proto_pbft_transport_proto_enumTypes[0]
}

func (x ViewChangeMsg_VCType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViewChangeMsg_VCType.Descriptor instead.
func (ViewChangeMsg_VCType) EnumDescriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{20, 0}
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_pbft_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Transaction) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ClientMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Txn           *Transaction           `protobuf:"bytes,3,opt,name=txn,proto3" json:"txn,omitempty"`
	ClientName    string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	Padding       string                 `protobuf:"bytes,5,opt,name=padding,proto3" json:"padding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMsg) Reset() {
	*x = ClientMsg{}
	mi := &file_proto_pbft_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMsg) ProtoMessage() {}

func (x *ClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMsg.ProtoReflect.Descriptor instead.
func (*ClientMsg) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMsg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClientMsg) GetTxn() *Transaction {
	if x != nil {
		return x.Txn
	}
	return nil
}

func (x *ClientMsg) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ClientMsg) GetPadding() string {
	if x != nil {
		return x.Padding
	}
	return ""
}

type ClientMsgSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ClientMsg             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMsgSignature) Reset() {
	*x = ClientMsgSignature{}
	mi := &file_proto_pbft_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMsgSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMsgSignature) ProtoMessage() {}

func (x *ClientMsgSignature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMsgSignature.ProtoReflect.Descriptor instead.
func (*ClientMsgSignature) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{2}
}

func (x *ClientMsgSignature) GetData() *ClientMsg {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClientMsgSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []*ClientMsgSignature  `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	mi := &file_proto_pbft_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{3}
}

func (x *RequestMessage) GetTxs() []*ClientMsgSignature {
	if x != nil {
		return x.Txs
	}
	return nil
}

type VCRunningStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []*ClientMsgSignature  `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	VcRunning     bool                   `protobuf:"varint,2,opt,name=vc_running,json=vcRunning,proto3" json:"vc_running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VCRunningStatus) Reset() {
	*x = VCRunningStatus{}
	mi := &file_proto_pbft_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VCRunningStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VCRunningStatus) ProtoMessage() {}

func (x *VCRunningStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VCRunningStatus.ProtoReflect.Descriptor instead.
func (*VCRunningStatus) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{4}
}

func (x *VCRunningStatus) GetTxs() []*ClientMsgSignature {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *VCRunningStatus) GetVcRunning() bool {
	if x != nil {
		return x.VcRunning
	}
	return false
}

type PreprepareMsg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	View            int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum          int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	ClientMsg       *ClientMsgSignature    `protobuf:"bytes,3,opt,name=client_msg,json=clientMsg,proto3" json:"client_msg,omitempty"`
	DigestClientMsg []byte                 `protobuf:"bytes,5,opt,name=digest_client_msg,json=digestClientMsg,proto3" json:"digest_client_msg,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreprepareMsg) Reset() {
	*x = PreprepareMsg{}
	mi := &file_proto_pbft_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprepareMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprepareMsg) ProtoMessage() {}

func (x *PreprepareMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprepareMsg.ProtoReflect.Descriptor instead.
func (*PreprepareMsg) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{5}
}

func (x *PreprepareMsg) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PreprepareMsg) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PreprepareMsg) GetClientMsg() *ClientMsgSignature {
	if x != nil {
		return x.ClientMsg
	}
	return nil
}

func (x *PreprepareMsg) GetDigestClientMsg() []byte {
	if x != nil {
		return x.DigestClientMsg
	}
	return nil
}

type PreprepareSignPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	View            int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum          int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	DigestClientMsg []byte                 `protobuf:"bytes,3,opt,name=digest_client_msg,json=digestClientMsg,proto3" json:"digest_client_msg,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreprepareSignPayload) Reset() {
	*x = PreprepareSignPayload{}
	mi := &file_proto_pbft_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprepareSignPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprepareSignPayload) ProtoMessage() {}

func (x *PreprepareSignPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprepareSignPayload.ProtoReflect.Descriptor instead.
func (*PreprepareSignPayload) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{6}
}

func (x *PreprepareSignPayload) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PreprepareSignPayload) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PreprepareSignPayload) GetDigestClientMsg() []byte {
	if x != nil {
		return x.DigestClientMsg
	}
	return nil
}

type PrepareMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum        int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	From          int32                  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMsg) Reset() {
	*x = PrepareMsg{}
	mi := &file_proto_pbft_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMsg) ProtoMessage() {}

func (x *PrepareMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMsg.ProtoReflect.Descriptor instead.
func (*PrepareMsg) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{7}
}

func (x *PrepareMsg) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PrepareMsg) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PrepareMsg) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PrepareMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

type CommitMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum        int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	From          int32                  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMsg) Reset() {
	*x = CommitMsg{}
	mi := &file_proto_pbft_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMsg) ProtoMessage() {}

func (x *CommitMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMsg.ProtoReflect.Descriptor instead.
func (*CommitMsg) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{8}
}

func (x *CommitMsg) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *CommitMsg) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *CommitMsg) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CommitMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

type CheckpointMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        int64                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	From          int32                  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointMsg) Reset() {
	*x = CheckpointMsg{}
	mi := &file_proto_pbft_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointMsg) ProtoMessage() {}

func (x *CheckpointMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointMsg.ProtoReflect.Descriptor instead.
func (*CheckpointMsg) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{9}
}

func (x *CheckpointMsg) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *CheckpointMsg) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CheckpointMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

type RequestStateTransferMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        int64                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	From          int32                  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestStateTransferMsg) Reset() {
	*x = RequestStateTransferMsg{}
	mi := &file_proto_pbft_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStateTransferMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStateTransferMsg) ProtoMessage() {}

func (x *RequestStateTransferMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStateTransferMsg.ProtoReflect.Descriptor instead.
func (*RequestStateTransferMsg) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{10}
}

func (x *RequestStateTransferMsg) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *RequestStateTransferMsg) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *RequestStateTransferMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

type StateTransferMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        int64                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	From          int32                  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Balances      map[string]string      `protobuf:"bytes,4,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateTransferMsg) Reset() {
	*x = StateTransferMsg{}
	mi := &file_proto_pbft_transport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateTransferMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateTransferMsg) ProtoMessage() {}

func (x *StateTransferMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateTransferMsg.ProtoReflect.Descriptor instead.
func (*StateTransferMsg) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{11}
}

func (x *StateTransferMsg) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *StateTransferMsg) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *StateTransferMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *StateTransferMsg) GetBalances() map[string]string {
	if x != nil {
		return x.Balances
	}
	return nil
}

type PreprepareMsgMini struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	View            int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum          int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	DigestClientMsg []byte                 `protobuf:"bytes,3,opt,name=digest_client_msg,json=digestClientMsg,proto3" json:"digest_client_msg,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreprepareMsgMini) Reset() {
	*x = PreprepareMsgMini{}
	mi := &file_proto_pbft_transport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprepareMsgMini) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprepareMsgMini) ProtoMessage() {}

func (x *PreprepareMsgMini) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprepareMsgMini.ProtoReflect.Descriptor instead.
func (*PreprepareMsgMini) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{12}
}

func (x *PreprepareMsgMini) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PreprepareMsgMini) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PreprepareMsgMini) GetDigestClientMsg() []byte {
	if x != nil {
		return x.DigestClientMsg
	}
	return nil
}

type PreprepareMsgSig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PreprepareMsgMini *PreprepareMsgMini     `protobuf:"bytes,1,opt,name=preprepare_msg_mini,json=preprepareMsgMini,proto3" json:"preprepare_msg_mini,omitempty"`
	Signature         []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	ActualMsg         *ClientMsgSignature    `protobuf:"bytes,3,opt,name=actual_msg,json=actualMsg,proto3" json:"actual_msg,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PreprepareMsgSig) Reset() {
	*x = PreprepareMsgSig{}
	mi := &file_proto_pbft_transport_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprepareMsgSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprepareMsgSig) ProtoMessage() {}

func (x *PreprepareMsgSig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprepareMsgSig.ProtoReflect.Descriptor instead.
func (*PreprepareMsgSig) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{13}
}

func (x *PreprepareMsgSig) GetPreprepareMsgMini() *PreprepareMsgMini {
	if x != nil {
		return x.PreprepareMsgMini
	}
	return nil
}

func (x *PreprepareMsgSig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PreprepareMsgSig) GetActualMsg() *ClientMsgSignature {
	if x != nil {
		return x.ActualMsg
	}
	return nil
}

type PrepareMsgSig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrepareMsg    *PrepareMsg            `protobuf:"bytes,1,opt,name=prepare_msg,json=prepareMsg,proto3" json:"prepare_msg,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMsgSig) Reset() {
	*x = PrepareMsgSig{}
	mi := &file_proto_pbft_transport_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMsgSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMsgSig) ProtoMessage() {}

func (x *PrepareMsgSig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMsgSig.ProtoReflect.Descriptor instead.
func (*PrepareMsgSig) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{14}
}

func (x *PrepareMsgSig) GetPrepareMsg() *PrepareMsg {
	if x != nil {
		return x.PrepareMsg
	}
	return nil
}

func (x *PrepareMsgSig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CheckpointMsgSig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointMsg *CheckpointMsg         `protobuf:"bytes,1,opt,name=checkpoint_msg,json=checkpointMsg,proto3" json:"checkpoint_msg,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointMsgSig) Reset() {
	*x = CheckpointMsgSig{}
	mi := &file_proto_pbft_transport_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointMsgSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointMsgSig) ProtoMessage() {}

func (x *CheckpointMsgSig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointMsgSig.ProtoReflect.Descriptor instead.
func (*CheckpointMsgSig) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{15}
}

func (x *CheckpointMsgSig) GetCheckpointMsg() *CheckpointMsg {
	if x != nil {
		return x.CheckpointMsg
	}
	return nil
}

func (x *CheckpointMsgSig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PreparedCert struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	PreprepareMsg *PreprepareMsgSig        `protobuf:"bytes,1,opt,name=preprepare_msg,json=preprepareMsg,proto3" json:"preprepare_msg,omitempty"`
	PrepareLog    map[int32]*PrepareMsgSig `protobuf:"bytes,2,rep,name=prepare_log,json=prepareLog,proto3" json:"prepare_log,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreparedCert) Reset() {
	*x = PreparedCert{}
	mi := &file_proto_pbft_transport_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparedCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparedCert) ProtoMessage() {}

func (x *PreparedCert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparedCert.ProtoReflect.Descriptor instead.
func (*PreparedCert) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{16}
}

func (x *PreparedCert) GetPreprepareMsg() *PreprepareMsgSig {
	if x != nil {
		return x.PreprepareMsg
	}
	return nil
}

func (x *PreparedCert) GetPrepareLog() map[int32]*PrepareMsgSig {
	if x != nil {
		return x.PrepareLog
	}
	return nil
}

type ElectionVCData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqVote       bool                   `protobuf:"varint,1,opt,name=req_vote,json=reqVote,proto3" json:"req_vote,omitempty"`
	GrantVote     bool                   `protobuf:"varint,2,opt,name=grant_vote,json=grantVote,proto3" json:"grant_vote,omitempty"`
	GrantTo       int32                  `protobuf:"varint,3,opt,name=grant_to,json=grantTo,proto3" json:"grant_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionVCData) Reset() {
	*x = ElectionVCData{}
	mi := &file_proto_pbft_transport_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionVCData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionVCData) ProtoMessage() {}

func (x *ElectionVCData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionVCData.ProtoReflect.Descriptor instead.
func (*ElectionVCData) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{17}
}

func (x *ElectionVCData) GetReqVote() bool {
	if x != nil {
		return x.ReqVote
	}
	return false
}

func (x *ElectionVCData) GetGrantVote() bool {
	if x != nil {
		return x.GrantVote
	}
	return false
}

func (x *ElectionVCData) GetGrantTo() int32 {
	if x != nil {
		return x.GrantTo
	}
	return 0
}

type RoundRobinVCData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantVote     bool                   `protobuf:"varint,1,opt,name=grant_vote,json=grantVote,proto3" json:"grant_vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundRobinVCData) Reset() {
	*x = RoundRobinVCData{}
	mi := &file_proto_pbft_transport_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundRobinVCData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundRobinVCData) ProtoMessage() {}

func (x *RoundRobinVCData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundRobinVCData.ProtoReflect.Descriptor instead.
func (*RoundRobinVCData) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{18}
}

func (x *RoundRobinVCData) GetGrantVote() bool {
	if x != nil {
		return x.GrantVote
	}
	return false
}

type WRRVCData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Throughput    float64                `protobuf:"fixed64,1,opt,name=throughput,proto3" json:"throughput,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WRRVCData) Reset() {
	*x = WRRVCData{}
	mi := &file_proto_pbft_transport_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WRRVCData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WRRVCData) ProtoMessage() {}

func (x *WRRVCData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WRRVCData.ProtoReflect.Descriptor instead.
func (*WRRVCData) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{19}
}

func (x *WRRVCData) GetThroughput() float64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

type ViewChangeMsg struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	ViewNumber          int64                   `protobuf:"varint,1,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	CheckpointSeqNumber int64                   `protobuf:"varint,2,opt,name=checkpoint_seq_number,json=checkpointSeqNumber,proto3" json:"checkpoint_seq_number,omitempty"`
	From                int32                   `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	PreparedCerts       map[int64]*PreparedCert `protobuf:"bytes,4,rep,name=prepared_certs,json=preparedCerts,proto3" json:"prepared_certs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	VcType              ViewChangeMsg_VCType    `protobuf:"varint,5,opt,name=vc_type,json=vcType,proto3,enum=pbft.transport.v1.ViewChangeMsg_VCType" json:"vc_type,omitempty"`
	// Types that are valid to be assigned to VcData:
	//
	//	*ViewChangeMsg_Election
	//	*ViewChangeMsg_RoundRobin
	//	*ViewChangeMsg_Wrr
	VcData           isViewChangeMsg_VcData `protobuf_oneof:"vc_data"`
	CheckpointDigest []byte                 `protobuf:"bytes,9,opt,name=checkpoint_digest,json=checkpointDigest,proto3" json:"checkpoint_digest,omitempty"`
	CheckpointProof  []*CheckpointMsgSig    `protobuf:"bytes,10,rep,name=checkpoint_proof,json=checkpointProof,proto3" json:"checkpoint_proof,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ViewChangeMsg) Reset() {
	*x = ViewChangeMsg{}
	mi := &file_proto_pbft_transport_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewChangeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewChangeMsg) ProtoMessage() {}

func (x *ViewChangeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewChangeMsg.ProtoReflect.Descriptor instead.
func (*ViewChangeMsg) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{20}
}

func (x *ViewChangeMsg) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *ViewChangeMsg) GetCheckpointSeqNumber() int64 {
	if x != nil {
		return x.CheckpointSeqNumber
	}
	return 0
}

func (x *ViewChangeMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ViewChangeMsg) GetPreparedCerts() map[int64]*PreparedCert {
	if x != nil {
		return x.PreparedCerts
	}
	return nil
}

func (x *ViewChangeMsg) GetVcType() ViewChangeMsg_VCType {
	if x != nil {
		return x.VcType
	}
	return ViewChangeMsg_VC_TYPE_UNSPECIFIED
}

func (x *ViewChangeMsg) GetVcData() isViewChangeMsg_VcData {
	if x != nil {
		return x.VcData
	}
	return nil
}

func (x *ViewChangeMsg) GetElection() *ElectionVCData {
	if x != nil {
		if x, ok := x.VcData.(*ViewChangeMsg_Election); ok {
			return x.Election
		}
	}
	return nil
}

func (x *ViewChangeMsg) GetRoundRobin() *RoundRobinVCData {
	if x != nil {
		if x, ok := x.VcData.(*ViewChangeMsg_RoundRobin); ok {
			return x.RoundRobin
		}
	}
	return nil
}

func (x *ViewChangeMsg) GetWrr() *WRRVCData {
	if x != nil {
		if x, ok := x.VcData.(*ViewChangeMsg_Wrr); ok {
			return x.Wrr
		}
	}
	return nil
}

func (x *ViewChangeMsg) GetCheckpointDigest() []byte {
	if x != nil {
		return x.CheckpointDigest
	}
	return nil
}

func (x *ViewChangeMsg) GetCheckpointProof() []*CheckpointMsgSig {
	if x != nil {
		return x.CheckpointProof
	}
	return nil
}

type isViewChangeMsg_VcData interface {
	isViewChangeMsg_VcData()
}

type ViewChangeMsg_Election struct {
	Election *ElectionVCData `protobuf:"bytes,6,opt,name=election,proto3,oneof"`
}

type ViewChangeMsg_RoundRobin struct {
	RoundRobin *RoundRobinVCData `protobuf:"bytes,7,opt,name=round_robin,json=roundRobin,proto3,oneof"`
}

type ViewChangeMsg_Wrr struct {
	Wrr *WRRVCData `protobuf:"bytes,8,opt,name=wrr,proto3,oneof"`
}

func (*ViewChangeMsg_Election) isViewChangeMsg_VcData() {}

func (*ViewChangeMsg_RoundRobin) isViewChangeMsg_VcData() {}

func (*ViewChangeMsg_Wrr) isViewChangeMsg_VcData() {}

type ViewChangeMsgSig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewChangeMsg *ViewChangeMsg         `protobuf:"bytes,1,opt,name=view_change_msg,json=viewChangeMsg,proto3" json:"view_change_msg,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewChangeMsgSig) Reset() {
	*x = ViewChangeMsgSig{}
	mi := &file_proto_pbft_transport_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewChangeMsgSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewChangeMsgSig) ProtoMessage() {}

func (x *ViewChangeMsgSig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewChangeMsgSig.ProtoReflect.Descriptor instead.
func (*ViewChangeMsgSig) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{21}
}

func (x *ViewChangeMsgSig) GetViewChangeMsg() *ViewChangeMsg {
	if x != nil {
		return x.ViewChangeMsg
	}
	return nil
}

func (x *ViewChangeMsgSig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type GrantVoteMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber    int64                  `protobuf:"varint,1,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	From          int32                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantVoteMsg) Reset() {
	*x = GrantVoteMsg{}
	mi := &file_proto_pbft_transport_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantVoteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantVoteMsg) ProtoMessage() {}

func (x *GrantVoteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantVoteMsg.ProtoReflect.Descriptor instead.
func (*GrantVoteMsg) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{22}
}

func (x *GrantVoteMsg) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *GrantVoteMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

type GrantVoteMsgSig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantVoteMsg  *GrantVoteMsg          `protobuf:"bytes,1,opt,name=grant_vote_msg,json=grantVoteMsg,proto3" json:"grant_vote_msg,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantVoteMsgSig) Reset() {
	*x = GrantVoteMsgSig{}
	mi := &file_proto_pbft_transport_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantVoteMsgSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantVoteMsgSig) ProtoMessage() {}

func (x *GrantVoteMsgSig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantVoteMsgSig.ProtoReflect.Descriptor instead.
func (*GrantVoteMsgSig) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{23}
}

func (x *GrantVoteMsgSig) GetGrantVoteMsg() *GrantVoteMsg {
	if x != nil {
		return x.GrantVoteMsg
	}
	return nil
}

func (x *GrantVoteMsgSig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type NewViewMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreprepareLog []*PreprepareMsgSig    `protobuf:"bytes,1,rep,name=preprepare_log,json=preprepareLog,proto3" json:"preprepare_log,omitempty"`
	ViewChangeLog []*ViewChangeMsgSig    `protobuf:"bytes,2,rep,name=view_change_log,json=viewChangeLog,proto3" json:"view_change_log,omitempty"`
	NewViewNumber int64                  `protobuf:"varint,3,opt,name=new_view_number,json=newViewNumber,proto3" json:"new_view_number,omitempty"`
	From          int32                  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	Throughput    float64                `protobuf:"fixed64,5,opt,name=throughput,proto3" json:"throughput,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewViewMsg) Reset() {
	*x = NewViewMsg{}
	mi := &file_proto_pbft_transport_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewMsg) ProtoMessage() {}

func (x *NewViewMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewMsg.ProtoReflect.Descriptor instead.
func (*NewViewMsg) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{24}
}

func (x *NewViewMsg) GetPreprepareLog() []*PreprepareMsgSig {
	if x != nil {
		return x.PreprepareLog
	}
	return nil
}

func (x *NewViewMsg) GetViewChangeLog() []*ViewChangeMsgSig {
	if x != nil {
		return x.ViewChangeLog
	}
	return nil
}

func (x *NewViewMsg) GetNewViewNumber() int64 {
	if x != nil {
		return x.NewViewNumber
	}
	return 0
}

func (x *NewViewMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *NewViewMsg) GetThroughput() float64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

type NewViewMsgSig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewViewMsg    *NewViewMsg            `protobuf:"bytes,1,opt,name=new_view_msg,json=newViewMsg,proto3" json:"new_view_msg,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewViewMsgSig) Reset() {
	*x = NewViewMsgSig{}
	mi := &file_proto_pbft_transport_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewMsgSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewMsgSig) ProtoMessage() {}

func (x *NewViewMsgSig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewMsgSig.ProtoReflect.Descriptor instead.
func (*NewViewMsgSig) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{25}
}

func (x *NewViewMsgSig) GetNewViewMsg() *NewViewMsg {
	if x != nil {
		return x.NewViewMsg
	}
	return nil
}

func (x *NewViewMsgSig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ReplyMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	To             string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From           string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	ClientMsg      *ClientMsg             `protobuf:"bytes,3,opt,name=client_msg,json=clientMsg,proto3" json:"client_msg,omitempty"`
	Success        bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ExecutedSeqNum int64                  `protobuf:"varint,6,opt,name=executed_seq_num,json=executedSeqNum,proto3" json:"executed_seq_num,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	mi := &file_proto_pbft_transport_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{26}
}

func (x *ReplyMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ReplyMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ReplyMessage) GetClientMsg() *ClientMsg {
	if x != nil {
		return x.ClientMsg
	}
	return nil
}

func (x *ReplyMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplyMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReplyMessage) GetExecutedSeqNum() int64 {
	if x != nil {
		return x.ExecutedSeqNum
	}
	return 0
}

type CommitTps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	ClientMsg     *ClientMsg             `protobuf:"bytes,3,opt,name=client_msg,json=clientMsg,proto3" json:"client_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTps) Reset() {
	*x = CommitTps{}
	mi := &file_proto_pbft_transport_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTps) ProtoMessage() {}

func (x *CommitTps) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTps.ProtoReflect.Descriptor instead.
func (*CommitTps) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{27}
}

func (x *CommitTps) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *CommitTps) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CommitTps) GetClientMsg() *ClientMsg {
	if x != nil {
		return x.ClientMsg
	}
	return nil
}

type LeaderIdUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	NewLeaderId   int32                  `protobuf:"varint,3,opt,name=new_leader_id,json=newLeaderId,proto3" json:"new_leader_id,omitempty"`
	View          int64                  `protobuf:"varint,4,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderIdUpdate) Reset() {
	*x = LeaderIdUpdate{}
	mi := &file_proto_pbft_transport_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderIdUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderIdUpdate) ProtoMessage() {}

func (x *LeaderIdUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderIdUpdate.ProtoReflect.Descriptor instead.
func (*LeaderIdUpdate) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{28}
}

func (x *LeaderIdUpdate) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *LeaderIdUpdate) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *LeaderIdUpdate) GetNewLeaderId() int32 {
	if x != nil {
		return x.NewLeaderId
	}
	return 0
}

func (x *LeaderIdUpdate) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

type CloseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseMessage) Reset() {
	*x = CloseMessage{}
	mi := &file_proto_pbft_transport_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseMessage) ProtoMessage() {}

func (x *CloseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseMessage.ProtoReflect.Descriptor instead.
func (*CloseMessage) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{29}
}

func (x *CloseMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CloseMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CloseMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MsgType   string                 `protobuf:"bytes,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	From      int32                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	Signature []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Request
	//	*Envelope_Preprepare
	//	*Envelope_Prepare
	//	*Envelope_Commit
	//	*Envelope_Reply
	//	*Envelope_Close
	//	*Envelope_ViewChange
	//	*Envelope_GrantVote
	//	*Envelope_NewView
	//	*Envelope_Checkpoint
	//	*Envelope_CommitTps
	//	*Envelope_LeaderIdUpdate
	//	*Envelope_VcRunningStatus
	//	*Envelope_RequestStateTransfer
	//	*Envelope_StateTransfer
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_pbft_transport_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{30}
}

func (x *Envelope) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *Envelope) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetRequest() *RequestMessage {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Envelope) GetPreprepare() *PreprepareMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Preprepare); ok {
			return x.Preprepare
		}
	}
	return nil
}

func (x *Envelope) GetPrepare() *PrepareMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Prepare); ok {
			return x.Prepare
		}
	}
	return nil
}

func (x *Envelope) GetCommit() *CommitMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *Envelope) GetReply() *ReplyMessage {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Reply); ok {
			return x.Reply
		}
	}
	return nil
}

func (x *Envelope) GetClose() *CloseMessage {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *Envelope) GetViewChange() *ViewChangeMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ViewChange); ok {
			return x.ViewChange
		}
	}
	return nil
}

func (x *Envelope) GetGrantVote() *GrantVoteMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_GrantVote); ok {
			return x.GrantVote
		}
	}
	return nil
}

func (x *Envelope) GetNewView() *NewViewMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_NewView); ok {
			return x.NewView
		}
	}
	return nil
}

func (x *Envelope) GetCheckpoint() *CheckpointMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Checkpoint); ok {
			return x.Checkpoint
		}
	}
	return nil
}

func (x *Envelope) GetCommitTps() *CommitTps {
	if x != nil {
		if x, ok := x.Body.(*Envelope_CommitTps); ok {
			return x.CommitTps
		}
	}
	return nil
}

func (x *Envelope) GetLeaderIdUpdate() *LeaderIdUpdate {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LeaderIdUpdate); ok {
			return x.LeaderIdUpdate
		}
	}
	return nil
}

func (x *Envelope) GetVcRunningStatus() *VCRunningStatus {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VcRunningStatus); ok {
			return x.VcRunningStatus
		}
	}
	return nil
}

func (x *Envelope) GetRequestStateTransfer() *RequestStateTransferMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_RequestStateTransfer); ok {
			return x.RequestStateTransfer
		}
	}
	return nil
}

func (x *Envelope) GetStateTransfer() *StateTransferMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_StateTransfer); ok {
			return x.StateTransfer
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Request struct {
	Request *RequestMessage `protobuf:"bytes,10,opt,name=request,proto3,oneof"`
}

type Envelope_Preprepare struct {
	Preprepare *PreprepareMsg `protobuf:"bytes,11,opt,name=preprepare,proto3,oneof"`
}

type Envelope_Prepare struct {
	Prepare *PrepareMsg `protobuf:"bytes,12,opt,name=prepare,proto3,oneof"`
}

type Envelope_Commit struct {
	Commit *CommitMsg `protobuf:"bytes,13,opt,name=commit,proto3,oneof"`
}

type Envelope_Reply struct {
	Reply *ReplyMessage `protobuf:"bytes,14,opt,name=reply,proto3,oneof"`
}

type Envelope_Close struct {
	Close *CloseMessage `protobuf:"bytes,15,opt,name=close,proto3,oneof"`
}

type Envelope_ViewChange struct {
	ViewChange *ViewChangeMsg `protobuf:"bytes,16,opt,name=view_change,json=viewChange,proto3,oneof"`
}

type Envelope_GrantVote struct {
	GrantVote *GrantVoteMsg `protobuf:"bytes,17,opt,name=grant_vote,json=grantVote,proto3,oneof"`
}

type Envelope_NewView struct {
	NewView *NewViewMsg `protobuf:"bytes,18,opt,name=new_view,json=newView,proto3,oneof"`
}

type Envelope_Checkpoint struct {
	Checkpoint *CheckpointMsg `protobuf:"bytes,19,opt,name=checkpoint,proto3,oneof"`
}

type Envelope_CommitTps struct {
	CommitTps *CommitTps `protobuf:"bytes,20,opt,name=commit_tps,json=commitTps,proto3,oneof"`
}

type Envelope_LeaderIdUpdate struct {
	LeaderIdUpdate *LeaderIdUpdate `protobuf:"bytes,21,opt,name=leader_id_update,json=leaderIdUpdate,proto3,oneof"`
}

type Envelope_VcRunningStatus struct {
	VcRunningStatus *VCRunningStatus `protobuf:"bytes,22,opt,name=vc_running_status,json=vcRunningStatus,proto3,oneof"`
}

type Envelope_RequestStateTransfer struct {
	RequestStateTransfer *RequestStateTransferMsg `protobuf:"bytes,23,opt,name=request_state_transfer,json=requestStateTransfer,proto3,oneof"`
}

type Envelope_StateTransfer struct {
	StateTransfer *StateTransferMsg `protobuf:"bytes,24,opt,name=state_transfer,json=stateTransfer,proto3,oneof"`
}

func (*Envelope_Request) isEnvelope_Body() {}

func (*Envelope_Preprepare) isEnvelope_Body() {}

func (*Envelope_Prepare) isEnvelope_Body() {}

func (*Envelope_Commit) isEnvelope_Body() {}

func (*Envelope_Reply) isEnvelope_Body() {}

func (*Envelope_Close) isEnvelope_Body() {}

func (*Envelope_ViewChange) isEnvelope_Body() {}

func (*Envelope_GrantVote) isEnvelope_Body() {}

func (*Envelope_NewView) isEnvelope_Body() {}

func (*Envelope_Checkpoint) isEnvelope_Body() {}

func (*Envelope_CommitTps) isEnvelope_Body() {}

func (*Envelope_LeaderIdUpdate) isEnvelope_Body() {}

func (*Envelope_VcRunningStatus) isEnvelope_Body() {}

func (*Envelope_RequestStateTransfer) isEnvelope_Body() {}

func (*Envelope_StateTransfer) isEnvelope_Body() {}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_pbft_transport_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_transport_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_pbft_transport_proto_rawDescGZIP(), []int{31}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_pbft_transport_proto protoreflect.FileDescriptor

const file_proto_pbft_transport_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/pbft_transport.proto\x12\x11pbft.transport.v1\"w\n" +
	"\vTransaction\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xa6\x01\n" +
	"\tClientMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x120\n" +
	"\x03txn\x18\x03 \x01(\v2\x1e.pbft.transport.v1.TransactionR\x03txn\x12\x1f\n" +
	"\vclient_name\x18\x04 \x01(\tR\n" +
	"clientName\x12\x18\n" +
	"\apadding\x18\x05 \x01(\tR\apadding\"d\n" +
	"\x12ClientMsgSignature\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.pbft.transport.v1.ClientMsgR\x04data\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"I\n" +
	"\x0eRequestMessage\x127\n" +
	"\x03txs\x18\x01 \x03(\v2%.pbft.transport.v1.ClientMsgSignatureR\x03txs\"i\n" +
	"\x0fVCRunningStatus\x127\n" +
	"\x03txs\x18\x01 \x03(\v2%.pbft.transport.v1.ClientMsgSignatureR\x03txs\x12\x1d\n" +
	"\n" +
	"vc_running\x18\x02 \x01(\bR\tvcRunning\"\xb4\x01\n" +
	"\rPreprepareMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12D\n" +
	"\n" +
	"client_msg\x18\x03 \x01(\v2%.pbft.transport.v1.ClientMsgSignatureR\tclientMsg\x12*\n" +
	"\x11digest_client_msg\x18\x05 \x01(\fR\x0fdigestClientMsgJ\x04\b\x04\x10\x05\"v\n" +
	"\x15PreprepareSignPayload\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12*\n" +
	"\x11digest_client_msg\x18\x03 \x01(\fR\x0fdigestClientMsgJ\x04\b\x04\x10\x05\"k\n" +
	"\n" +
	"PrepareMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x12\n" +
	"\x04from\x18\x04 \x01(\x05R\x04fromJ\x04\b\x05\x10\x06\"j\n" +
	"\tCommitMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x12\n" +
	"\x04from\x18\x04 \x01(\x05R\x04fromJ\x04\b\x05\x10\x06\"T\n" +
	"\rCheckpointMsg\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x03R\x06seqNum\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x05R\x04from\"^\n" +
	"\x17RequestStateTransferMsg\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x03R\x06seqNum\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x05R\x04from\"\xe3\x01\n" +
	"\x10StateTransferMsg\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x03R\x06seqNum\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x05R\x04from\x12M\n" +
	"\bbalances\x18\x04 \x03(\v21.pbft.transport.v1.StateTransferMsg.BalancesEntryR\bbalances\x1a;\n" +
	"\rBalancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x11PreprepareMsgMini\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12*\n" +
	"\x11digest_client_msg\x18\x03 \x01(\fR\x0fdigestClientMsg\"\xcc\x01\n" +
	"\x10PreprepareMsgSig\x12T\n" +
	"\x13preprepare_msg_mini\x18\x01 \x01(\v2$.pbft.transport.v1.PreprepareMsgMiniR\x11preprepareMsgMini\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12D\n" +
	"\n" +
	"actual_msg\x18\x03 \x01(\v2%.pbft.transport.v1.ClientMsgSignatureR\tactualMsg\"m\n" +
	"\rPrepareMsgSig\x12>\n" +
	"\vprepare_msg\x18\x01 \x01(\v2\x1d.pbft.transport.v1.PrepareMsgR\n" +
	"prepareMsg\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"y\n" +
	"\x10CheckpointMsgSig\x12G\n" +
	"\x0echeckpoint_msg\x18\x01 \x01(\v2 .pbft.transport.v1.CheckpointMsgR\rcheckpointMsg\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\x8d\x02\n" +
	"\fPreparedCert\x12J\n" +
	"\x0epreprepare_msg\x18\x01 \x01(\v2#.pbft.transport.v1.PreprepareMsgSigR\rpreprepareMsg\x12P\n" +
	"\vprepare_log\x18\x02 \x03(\v2/.pbft.transport.v1.PreparedCert.PrepareLogEntryR\n" +
	"prepareLog\x1a_\n" +
	"\x0fPrepareLogEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .pbft.transport.v1.PrepareMsgSigR\x05value:\x028\x01\"e\n" +
	"\x0eElectionVCData\x12\x19\n" +
	"\breq_vote\x18\x01 \x01(\bR\areqVote\x12\x1d\n" +
	"\n" +
	"grant_vote\x18\x02 \x01(\bR\tgrantVote\x12\x19\n" +
	"\bgrant_to\x18\x03 \x01(\x05R\agrantTo\"1\n" +
	"\x10RoundRobinVCData\x12\x1d\n" +
	"\n" +
	"grant_vote\x18\x01 \x01(\bR\tgrantVote\"+\n" +
	"\tWRRVCData\x12\x1e\n" +
	"\n" +
	"throughput\x18\x01 \x01(\x01R\n" +
	"throughput\"\x9f\x06\n" +
	"\rViewChangeMsg\x12\x1f\n" +
	"\vview_number\x18\x01 \x01(\x03R\n" +
	"viewNumber\x122\n" +
	"\x15checkpoint_seq_number\x18\x02 \x01(\x03R\x13checkpointSeqNumber\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x05R\x04from\x12Z\n" +
	"\x0eprepared_certs\x18\x04 \x03(\v23.pbft.transport.v1.ViewChangeMsg.PreparedCertsEntryR\rpreparedCerts\x12@\n" +
	"\avc_type\x18\x05 \x01(\x0e2'.pbft.transport.v1.ViewChangeMsg.VCTypeR\x06vcType\x12?\n" +
	"\belection\x18\x06 \x01(\v2!.pbft.transport.v1.ElectionVCDataH\x00R\belection\x12F\n" +
	"\vround_robin\x18\a \x01(\v2#.pbft.transport.v1.RoundRobinVCDataH\x00R\n" +
	"roundRobin\x120\n" +
	"\x03wrr\x18\b \x01(\v2\x1c.pbft.transport.v1.WRRVCDataH\x00R\x03wrr\x12+\n" +
	"\x11checkpoint_digest\x18\t \x01(\fR\x10checkpointDigest\x12N\n" +
	"\x10checkpoint_proof\x18\n" +
	" \x03(\v2#.pbft.transport.v1.CheckpointMsgSigR\x0fcheckpointProof\x1aa\n" +
	"\x12PreparedCertsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.pbft.transport.v1.PreparedCertR\x05value:\x028\x01\"a\n" +
	"\x06VCType\x12\x17\n" +
	"\x13VC_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10VC_TYPE_ELECTION\x10\x01\x12\x17\n" +
	"\x13VC_TYPE_ROUND_ROBIN\x10\x02\x12\x0f\n" +
	"\vVC_TYPE_WRR\x10\x03B\t\n" +
	"\avc_data\"z\n" +
	"\x10ViewChangeMsgSig\x12H\n" +
	"\x0fview_change_msg\x18\x01 \x01(\v2 .pbft.transport.v1.ViewChangeMsgR\rviewChangeMsg\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"C\n" +
	"\fGrantVoteMsg\x12\x1f\n" +
	"\vview_number\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x05R\x04from\"v\n" +
	"\x0fGrantVoteMsgSig\x12E\n" +
	"\x0egrant_vote_msg\x18\x01 \x01(\v2\x1f.pbft.transport.v1.GrantVoteMsgR\fgrantVoteMsg\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\x81\x02\n" +
	"\n" +
	"NewViewMsg\x12J\n" +
	"\x0epreprepare_log\x18\x01 \x03(\v2#.pbft.transport.v1.PreprepareMsgSigR\rpreprepareLog\x12K\n" +
	"\x0fview_change_log\x18\x02 \x03(\v2#.pbft.transport.v1.ViewChangeMsgSigR\rviewChangeLog\x12&\n" +
	"\x0fnew_view_number\x18\x03 \x01(\x03R\rnewViewNumber\x12\x12\n" +
	"\x04from\x18\x04 \x01(\x05R\x04from\x12\x1e\n" +
	"\n" +
	"throughput\x18\x05 \x01(\x01R\n" +
	"throughput\"n\n" +
	"\rNewViewMsgSig\x12?\n" +
	"\fnew_view_msg\x18\x01 \x01(\v2\x1d.pbft.transport.v1.NewViewMsgR\n" +
	"newViewMsg\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xc9\x01\n" +
	"\fReplyMessage\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12;\n" +
	"\n" +
	"client_msg\x18\x03 \x01(\v2\x1c.pbft.transport.v1.ClientMsgR\tclientMsg\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12(\n" +
	"\x10executed_seq_num\x18\x06 \x01(\x03R\x0eexecutedSeqNum\"l\n" +
	"\tCommitTps\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12;\n" +
	"\n" +
	"client_msg\x18\x03 \x01(\v2\x1c.pbft.transport.v1.ClientMsgR\tclientMsg\"l\n" +
	"\x0eLeaderIdUpdate\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\"\n" +
	"\rnew_leader_id\x18\x03 \x01(\x05R\vnewLeaderId\x12\x12\n" +
	"\x04view\x18\x04 \x01(\x03R\x04view\"P\n" +
	"\fCloseMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"\xe0\b\n" +
	"\bEnvelope\x12\x19\n" +
	"\bmsg_type\x18\x01 \x01(\tR\amsgType\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x05R\x04from\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12=\n" +
	"\arequest\x18\n" +
	" \x01(\v2!.pbft.transport.v1.RequestMessageH\x00R\arequest\x12B\n" +
	"\n" +
	"preprepare\x18\v \x01(\v2 .pbft.transport.v1.PreprepareMsgH\x00R\n" +
	"preprepare\x129\n" +
	"\aprepare\x18\f \x01(\v2\x1d.pbft.transport.v1.PrepareMsgH\x00R\aprepare\x126\n" +
	"\x06commit\x18\r \x01(\v2\x1c.pbft.transport.v1.CommitMsgH\x00R\x06commit\x127\n" +
	"\x05reply\x18\x0e \x01(\v2\x1f.pbft.transport.v1.ReplyMessageH\x00R\x05reply\x127\n" +
	"\x05close\x18\x0f \x01(\v2\x1f.pbft.transport.v1.CloseMessageH\x00R\x05close\x12C\n" +
	"\vview_change\x18\x10 \x01(\v2 .pbft.transport.v1.ViewChangeMsgH\x00R\n" +
	"viewChange\x12@\n" +
	"\n" +
	"grant_vote\x18\x11 \x01(\v2\x1f.pbft.transport.v1.GrantVoteMsgH\x00R\tgrantVote\x12:\n" +
	"\bnew_view\x18\x12 \x01(\v2\x1d.pbft.transport.v1.NewViewMsgH\x00R\anewView\x12B\n" +
	"\n" +
	"checkpoint\x18\x13 \x01(\v2 .pbft.transport.v1.CheckpointMsgH\x00R\n" +
	"checkpoint\x12=\n" +
	"\n" +
	"commit_tps\x18\x14 \x01(\v2\x1c.pbft.transport.v1.CommitTpsH\x00R\tcommitTps\x12M\n" +
	"\x10leader_id_update\x18\x15 \x01(\v2!.pbft.transport.v1.LeaderIdUpdateH\x00R\x0eleaderIdUpdate\x12P\n" +
	"\x11vc_running_status\x18\x16 \x01(\v2\".pbft.transport.v1.VCRunningStatusH\x00R\x0fvcRunningStatus\x12b\n" +
	"\x16request_state_transfer\x18\x17 \x01(\v2*.pbft.transport.v1.RequestStateTransferMsgH\x00R\x14requestStateTransfer\x12L\n" +
	"\x0estate_transfer\x18\x18 \x01(\v2#.pbft.transport.v1.StateTransferMsgH\x00R\rstateTransferB\x06\n" +
	"\x04body\"+\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xa2\x01\n" +
	"\rPBFTTransport\x12>\n" +
	"\aDeliver\x12\x1b.pbft.transport.v1.Envelope\x1a\x16.pbft.transport.v1.Ack\x12Q\n" +
	"\x11ClientNodeChannel\x12\x1b.pbft.transport.v1.Envelope\x1a\x1b.pbft.transport.v1.Envelope(\x010\x01B7Z5github.com/michael112233/pbft/transportpb;transportpbb\x06proto3"

var (
	file_proto_pbft_transport_proto_rawDescOnce sync.Once
	file_proto_pbft_transport_proto_rawDescData []byte
)

func file_proto_pbft_transport_proto_rawDescGZIP() []byte {
	file_proto_pbft_transport_proto_rawDescOnce.Do(func() {
		file_proto_pbft_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pbft_transport_proto_rawDesc), len(file_proto_pbft_transport_proto_rawDesc)))
	})
	return file_proto_pbft_transport_proto_rawDescData
}

var file_proto_pbft_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_pbft_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_pbft_transport_proto_goTypes = []any{
	(ViewChangeMsg_VCType)(0),       // 0: pbft.transport.v1.ViewChangeMsg.VCType
	(*Transaction)(nil),             // 1: pbft.transport.v1.Transaction
	(*ClientMsg)(nil),               // 2: pbft.transport.v1.ClientMsg
	(*ClientMsgSignature)(nil),      // 3: pbft.transport.v1.ClientMsgSignature
	(*RequestMessage)(nil),          // 4: pbft.transport.v1.RequestMessage
	(*VCRunningStatus)(nil),         // 5: pbft.transport.v1.VCRunningStatus
	(*PreprepareMsg)(nil),           // 6: pbft.transport.v1.PreprepareMsg
	(*PreprepareSignPayload)(nil),   // 7: pbft.transport.v1.PreprepareSignPayload
	(*PrepareMsg)(nil),              // 8: pbft.transport.v1.PrepareMsg
	(*CommitMsg)(nil),               // 9: pbft.transport.v1.CommitMsg
	(*CheckpointMsg)(nil),           // 10: pbft.transport.v1.CheckpointMsg
	(*RequestStateTransferMsg)(nil), // 11: pbft.transport.v1.RequestStateTransferMsg
	(*StateTransferMsg)(nil),        // 12: pbft.transport.v1.StateTransferMsg
	(*PreprepareMsgMini)(nil),       // 13: pbft.transport.v1.PreprepareMsgMini
	(*PreprepareMsgSig)(nil),        // 14: pbft.transport.v1.PreprepareMsgSig
	(*PrepareMsgSig)(nil),           // 15: pbft.transport.v1.PrepareMsgSig
	(*CheckpointMsgSig)(nil),        // 16: pbft.transport.v1.CheckpointMsgSig
	(*PreparedCert)(nil),            // 17: pbft.transport.v1.PreparedCert
	(*ElectionVCData)(nil),          // 18: pbft.transport.v1.ElectionVCData
	(*RoundRobinVCData)(nil),        // 19: pbft.transport.v1.RoundRobinVCData
	(*WRRVCData)(nil),               // 20: pbft.transport.v1.WRRVCData
	(*ViewChangeMsg)(nil),           // 21: pbft.transport.v1.ViewChangeMsg
	(*ViewChangeMsgSig)(nil),        // 22: pbft.transport.v1.ViewChangeMsgSig
	(*GrantVoteMsg)(nil),            // 23: pbft.transport.v1.GrantVoteMsg
	(*GrantVoteMsgSig)(nil),         // 24: pbft.transport.v1.GrantVoteMsgSig
	(*NewViewMsg)(nil),              // 25: pbft.transport.v1.NewViewMsg
	(*NewViewMsgSig)(nil),           // 26: pbft.transport.v1.NewViewMsgSig
	(*ReplyMessage)(nil),            // 27: pbft.transport.v1.ReplyMessage
	(*CommitTps)(nil),               // 28: pbft.transport.v1.CommitTps
	(*LeaderIdUpdate)(nil),          // 29: pbft.transport.v1.LeaderIdUpdate
	(*CloseMessage)(nil),            // 30: pbft.transport.v1.CloseMessage
	(*Envelope)(nil),                // 31: pbft.transport.v1.Envelope
	(*Ack)(nil),                     // 32: pbft.transport.v1.Ack
	nil,                             // 33: pbft.transport.v1.StateTransferMsg.BalancesEntry
	nil,                             // 34: pbft.transport.v1.PreparedCert.PrepareLogEntry
	nil,                             // 35: pbft.transport.v1.ViewChangeMsg.PreparedCertsEntry
}
var file_proto_pbft_transport_proto_depIdxs = []int32{
	1,  // 0: pbft.transport.v1.ClientMsg.txn:type_name -> pbft.transport.v1.Transaction
	2,  // 1: pbft.transport.v1.ClientMsgSignature.data:type_name -> pbft.transport.v1.ClientMsg
	3,  // 2: pbft.transport.v1.RequestMessage.txs:type_name -> pbft.transport.v1.ClientMsgSignature
	3,  // 3: pbft.transport.v1.VCRunningStatus.txs:type_name -> pbft.transport.v1.ClientMsgSignature
	3,  // 4: pbft.transport.v1.PreprepareMsg.client_msg:type_name -> pbft.transport.v1.ClientMsgSignature
	33, // 5: pbft.transport.v1.StateTransferMsg.balances:type_name -> pbft.transport.v1.StateTransferMsg.BalancesEntry
	13, // 6: pbft.transport.v1.PreprepareMsgSig.preprepare_msg_mini:type_name -> pbft.transport.v1.PreprepareMsgMini
	3,  // 7: pbft.transport.v1.PreprepareMsgSig.actual_msg:type_name -> pbft.transport.v1.ClientMsgSignature
	8,  // 8: pbft.transport.v1.PrepareMsgSig.prepare_msg:type_name -> pbft.transport.v1.PrepareMsg
	10, // 9: pbft.transport.v1.CheckpointMsgSig.checkpoint_msg:type_name -> pbft.transport.v1.CheckpointMsg
	14, // 10: pbft.transport.v1.PreparedCert.preprepare_msg:type_name -> pbft.transport.v1.PreprepareMsgSig
	34, // 11: pbft.transport.v1.PreparedCert.prepare_log:type_name -> pbft.transport.v1.PreparedCert.PrepareLogEntry
	35, // 12: pbft.transport.v1.ViewChangeMsg.prepared_certs:type_name -> pbft.transport.v1.ViewChangeMsg.PreparedCertsEntry
	0,  // 13: pbft.transport.v1.ViewChangeMsg.vc_type:type_name -> pbft.transport.v1.ViewChangeMsg.VCType
	18, // 14: pbft.transport.v1.ViewChangeMsg.election:type_name -> pbft.transport.v1.ElectionVCData
	19, // 15: pbft.transport.v1.ViewChangeMsg.round_robin:type_name -> pbft.transport.v1.RoundRobinVCData
	20, // 16: pbft.transport.v1.ViewChangeMsg.wrr:type_name -> pbft.transport.v1.WRRVCData
	16, // 17: pbft.transport.v1.ViewChangeMsg.checkpoint_proof:type_name -> pbft.transport.v1.CheckpointMsgSig
	21, // 18: pbft.transport.v1.ViewChangeMsgSig.view_change_msg:type_name -> pbft.transport.v1.ViewChangeMsg
	23, // 19: pbft.transport.v1.GrantVoteMsgSig.grant_vote_msg:type_name -> pbft.transport.v1.GrantVoteMsg
	14, // 20: pbft.transport.v1.NewViewMsg.preprepare_log:type_name -> pbft.transport.v1.PreprepareMsgSig
	22, // 21: pbft.transport.v1.NewViewMsg.view_change_log:type_name -> pbft.transport.v1.ViewChangeMsgSig
	25, // 22: pbft.transport.v1.NewViewMsgSig.new_view_msg:type_name -> pbft.transport.v1.NewViewMsg
	2,  // 23: pbft.transport.v1.ReplyMessage.client_msg:type_name -> pbft.transport.v1.ClientMsg
	2,  // 24: pbft.transport.v1.CommitTps.client_msg:type_name -> pbft.transport.v1.ClientMsg
	4,  // 25: pbft.transport.v1.Envelope.request:type_name -> pbft.transport.v1.RequestMessage
	6,  // 26: pbft.transport.v1.Envelope.preprepare:type_name -> pbft.transport.v1.PreprepareMsg
	8,  // 27: pbft.transport.v1.Envelope.prepare:type_name -> pbft.transport.v1.PrepareMsg
	9,  // 28: pbft.transport.v1.Envelope.commit:type_name -> pbft.transport.v1.CommitMsg
	27, // 29: pbft.transport.v1.Envelope.reply:type_name -> pbft.transport.v1.ReplyMessage
	30, // 30: pbft.transport.v1.Envelope.close:type_name -> pbft.transport.v1.CloseMessage
	21, // 31: pbft.transport.v1.Envelope.view_change:type_name -> pbft.transport.v1.ViewChangeMsg
	23, // 32: pbft.transport.v1.Envelope.grant_vote:type_name -> pbft.transport.v1.GrantVoteMsg
	25, // 33: pbft.transport.v1.Envelope.new_view:type_name -> pbft.transport.v1.NewViewMsg
	10, // 34: pbft.transport.v1.Envelope.checkpoint:type_name -> pbft.transport.v1.CheckpointMsg
	28, // 35: pbft.transport.v1.Envelope.commit_tps:type_name -> pbft.transport.v1.CommitTps
	29, // 36: pbft.transport.v1.Envelope.leader_id_update:type_name -> pbft.transport.v1.LeaderIdUpdate
	5,  // 37: pbft.transport.v1.Envelope.vc_running_status:type_name -> pbft.transport.v1.VCRunningStatus
	11, // 38: pbft.transport.v1.Envelope.request_state_transfer:type_name -> pbft.transport.v1.RequestStateTransferMsg
	12, // 39: pbft.transport.v1.Envelope.state_transfer:type_name -> pbft.transport.v1.StateTransferMsg
	15, // 40: pbft.transport.v1.PreparedCert.PrepareLogEntry.value:type_name -> pbft.transport.v1.PrepareMsgSig
	17, // 41: pbft.transport.v1.ViewChangeMsg.PreparedCertsEntry.value:type_name -> pbft.transport.v1.PreparedCert
	31, // 42: pbft.transport.v1.PBFTTransport.Deliver:input_type -> pbft.transport.v1.Envelope
	31, // 43: pbft.transport.v1.PBFTTransport.ClientNodeChannel:input_type -> pbft.transport.v1.Envelope
	32, // 44: pbft.transport.v1.PBFTTransport.Deliver:output_type -> pbft.transport.v1.Ack
	31, // 45: pbft.transport.v1.PBFTTransport.ClientNodeChannel:output_type -> pbft.transport.v1.Envelope
	44, // [44:46] is the sub-list for method output_type
	42, // [42:44] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_proto_pbft_transport_proto_init() }
func file_proto_pbft_transport_proto_init() {
	if File_proto_pbft_transport_proto != nil {
		return
	}
	file_proto_pbft_transport_proto_msgTypes[20].OneofWrappers = []any{
		(*ViewChangeMsg_Election)(nil),
		(*ViewChangeMsg_RoundRobin)(nil),
		(*ViewChangeMsg_Wrr)(nil),
	}
	file_proto_pbft_transport_proto_msgTypes[30].OneofWrappers = []any{
		(*Envelope_Request)(nil),
		(*Envelope_Preprepare)(nil),
		(*Envelope_Prepare)(nil),
		(*Envelope_Commit)(nil),
		(*Envelope_Reply)(nil),
		(*Envelope_Close)(nil),
		(*Envelope_ViewChange)(nil),
		(*Envelope_GrantVote)(nil),
		(*Envelope_NewView)(nil),
		(*Envelope_Checkpoint)(nil),
		(*Envelope_CommitTps)(nil),
		(*Envelope_LeaderIdUpdate)(nil),
		(*Envelope_VcRunningStatus)(nil),
		(*Envelope_RequestStateTransfer)(nil),
		(*Envelope_StateTransfer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pbft_transport_proto_rawDesc), len(file_proto_pbft_transport_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pbft_transport_proto_goTypes,
		DependencyIndexes: file_proto_pbft_transport_proto_depIdxs,
		EnumInfos:         file_proto_pbft_transport_proto_enumTypes,
		MessageInfos:      file_proto_pbft_transport_proto_msgTypes,
	}.Build()
	File_proto_pbft_transport_proto = out.File
	file_proto_pbft_transport_proto_goTypes = nil
	file_proto_pbft_transport_proto_depIdxs = nil
}
