// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pbft_transport.proto

package transportpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_pbft_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Transaction) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type ClientMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Txn           *Transaction           `protobuf:"bytes,3,opt,name=txn,proto3" json:"txn,omitempty"`
	ClientName    string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	Padding       string                 `protobuf:"bytes,5,opt,name=padding,proto3" json:"padding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMsg) Reset() {
	*x = ClientMsg{}
	mi := &file_pbft_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMsg) ProtoMessage() {}

func (x *ClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMsg.ProtoReflect.Descriptor instead.
func (*ClientMsg) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMsg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientMsg) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ClientMsg) GetTxn() *Transaction {
	if x != nil {
		return x.Txn
	}
	return nil
}

func (x *ClientMsg) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ClientMsg) GetPadding() string {
	if x != nil {
		return x.Padding
	}
	return ""
}

type ClientMsgReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Txn           *Transaction           `protobuf:"bytes,3,opt,name=txn,proto3" json:"txn,omitempty"`
	ClientName    string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMsgReply) Reset() {
	*x = ClientMsgReply{}
	mi := &file_pbft_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMsgReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMsgReply) ProtoMessage() {}

func (x *ClientMsgReply) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMsgReply.ProtoReflect.Descriptor instead.
func (*ClientMsgReply) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{2}
}

func (x *ClientMsgReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientMsgReply) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ClientMsgReply) GetTxn() *Transaction {
	if x != nil {
		return x.Txn
	}
	return nil
}

func (x *ClientMsgReply) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

type ClientMsgSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ClientMsg             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMsgSignature) Reset() {
	*x = ClientMsgSignature{}
	mi := &file_pbft_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMsgSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMsgSignature) ProtoMessage() {}

func (x *ClientMsgSignature) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMsgSignature.ProtoReflect.Descriptor instead.
func (*ClientMsgSignature) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{3}
}

func (x *ClientMsgSignature) GetData() *ClientMsg {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClientMsgSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []*ClientMsgSignature  `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	MsgType       string                 `protobuf:"bytes,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	mi := &file_pbft_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{4}
}

func (x *RequestMessage) GetTxs() []*ClientMsgSignature {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *RequestMessage) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

// ClientBatchDigestPayload is the canonical protobuf representation hashed for
// a batch. Client signatures are deliberately excluded and verified
// separately.
type ClientBatchDigestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgs    []*ClientMsg           `protobuf:"bytes,1,rep,name=client_msgs,json=clientMsgs,proto3" json:"client_msgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientBatchDigestPayload) Reset() {
	*x = ClientBatchDigestPayload{}
	mi := &file_pbft_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientBatchDigestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBatchDigestPayload) ProtoMessage() {}

func (x *ClientBatchDigestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBatchDigestPayload.ProtoReflect.Descriptor instead.
func (*ClientBatchDigestPayload) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{5}
}

func (x *ClientBatchDigestPayload) GetClientMsgs() []*ClientMsg {
	if x != nil {
		return x.ClientMsgs
	}
	return nil
}

type VCRunningStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []*ClientMsgSignature  `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	VcRunning     bool                   `protobuf:"varint,2,opt,name=vc_running,json=vcRunning,proto3" json:"vc_running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VCRunningStatus) Reset() {
	*x = VCRunningStatus{}
	mi := &file_pbft_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VCRunningStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VCRunningStatus) ProtoMessage() {}

func (x *VCRunningStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VCRunningStatus.ProtoReflect.Descriptor instead.
func (*VCRunningStatus) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{6}
}

func (x *VCRunningStatus) GetTxs() []*ClientMsgSignature {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *VCRunningStatus) GetVcRunning() bool {
	if x != nil {
		return x.VcRunning
	}
	return false
}

type PreprepareMsg struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	View                       int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum                     int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	ClientMsg                  []*ClientMsgSignature  `protobuf:"bytes,3,rep,name=client_msg,json=clientMsg,proto3" json:"client_msg,omitempty"`
	DigestClientMsg            []byte                 `protobuf:"bytes,5,opt,name=digest_client_msg,json=digestClientMsg,proto3" json:"digest_client_msg,omitempty"`
	DigestIndividualClientMsgs [][]byte               `protobuf:"bytes,6,rep,name=digest_individual_client_msgs,json=digestIndividualClientMsgs,proto3" json:"digest_individual_client_msgs,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *PreprepareMsg) Reset() {
	*x = PreprepareMsg{}
	mi := &file_pbft_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprepareMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprepareMsg) ProtoMessage() {}

func (x *PreprepareMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprepareMsg.ProtoReflect.Descriptor instead.
func (*PreprepareMsg) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{7}
}

func (x *PreprepareMsg) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PreprepareMsg) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PreprepareMsg) GetClientMsg() []*ClientMsgSignature {
	if x != nil {
		return x.ClientMsg
	}
	return nil
}

func (x *PreprepareMsg) GetDigestClientMsg() []byte {
	if x != nil {
		return x.DigestClientMsg
	}
	return nil
}

func (x *PreprepareMsg) GetDigestIndividualClientMsgs() [][]byte {
	if x != nil {
		return x.DigestIndividualClientMsgs
	}
	return nil
}

type PreprepareSignPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	View            int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum          int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	DigestClientMsg []byte                 `protobuf:"bytes,3,opt,name=digest_client_msg,json=digestClientMsg,proto3" json:"digest_client_msg,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreprepareSignPayload) Reset() {
	*x = PreprepareSignPayload{}
	mi := &file_pbft_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprepareSignPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprepareSignPayload) ProtoMessage() {}

func (x *PreprepareSignPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprepareSignPayload.ProtoReflect.Descriptor instead.
func (*PreprepareSignPayload) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{8}
}

func (x *PreprepareSignPayload) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PreprepareSignPayload) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PreprepareSignPayload) GetDigestClientMsg() []byte {
	if x != nil {
		return x.DigestClientMsg
	}
	return nil
}

type PrepareMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum        int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	From          int32                  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMsg) Reset() {
	*x = PrepareMsg{}
	mi := &file_pbft_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMsg) ProtoMessage() {}

func (x *PrepareMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMsg.ProtoReflect.Descriptor instead.
func (*PrepareMsg) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{9}
}

func (x *PrepareMsg) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PrepareMsg) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PrepareMsg) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PrepareMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

type CommitMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum        int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	From          int32                  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMsg) Reset() {
	*x = CommitMsg{}
	mi := &file_pbft_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMsg) ProtoMessage() {}

func (x *CommitMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMsg.ProtoReflect.Descriptor instead.
func (*CommitMsg) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{10}
}

func (x *CommitMsg) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *CommitMsg) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *CommitMsg) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CommitMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

type PreprepareMsgMini struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	View                       int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	SeqNum                     int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	DigestClientMsg            []byte                 `protobuf:"bytes,3,opt,name=digest_client_msg,json=digestClientMsg,proto3" json:"digest_client_msg,omitempty"`
	DigestIndividualClientMsgs [][]byte               `protobuf:"bytes,4,rep,name=digest_individual_client_msgs,json=digestIndividualClientMsgs,proto3" json:"digest_individual_client_msgs,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *PreprepareMsgMini) Reset() {
	*x = PreprepareMsgMini{}
	mi := &file_pbft_transport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprepareMsgMini) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprepareMsgMini) ProtoMessage() {}

func (x *PreprepareMsgMini) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprepareMsgMini.ProtoReflect.Descriptor instead.
func (*PreprepareMsgMini) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{11}
}

func (x *PreprepareMsgMini) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PreprepareMsgMini) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PreprepareMsgMini) GetDigestClientMsg() []byte {
	if x != nil {
		return x.DigestClientMsg
	}
	return nil
}

func (x *PreprepareMsgMini) GetDigestIndividualClientMsgs() [][]byte {
	if x != nil {
		return x.DigestIndividualClientMsgs
	}
	return nil
}

type PreprepareMsgSig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PreprepareMsgMini *PreprepareMsgMini     `protobuf:"bytes,1,opt,name=preprepare_msg_mini,json=preprepareMsgMini,proto3" json:"preprepare_msg_mini,omitempty"`
	Signature         []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	ActualMsg         *ClientMsgSignature    `protobuf:"bytes,3,opt,name=actual_msg,json=actualMsg,proto3" json:"actual_msg,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PreprepareMsgSig) Reset() {
	*x = PreprepareMsgSig{}
	mi := &file_pbft_transport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprepareMsgSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprepareMsgSig) ProtoMessage() {}

func (x *PreprepareMsgSig) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprepareMsgSig.ProtoReflect.Descriptor instead.
func (*PreprepareMsgSig) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{12}
}

func (x *PreprepareMsgSig) GetPreprepareMsgMini() *PreprepareMsgMini {
	if x != nil {
		return x.PreprepareMsgMini
	}
	return nil
}

func (x *PreprepareMsgSig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PreprepareMsgSig) GetActualMsg() *ClientMsgSignature {
	if x != nil {
		return x.ActualMsg
	}
	return nil
}

type PrepareMsgSig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrepareMsg    *PrepareMsg            `protobuf:"bytes,1,opt,name=prepare_msg,json=prepareMsg,proto3" json:"prepare_msg,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMsgSig) Reset() {
	*x = PrepareMsgSig{}
	mi := &file_pbft_transport_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMsgSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMsgSig) ProtoMessage() {}

func (x *PrepareMsgSig) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMsgSig.ProtoReflect.Descriptor instead.
func (*PrepareMsgSig) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{13}
}

func (x *PrepareMsgSig) GetPrepareMsg() *PrepareMsg {
	if x != nil {
		return x.PrepareMsg
	}
	return nil
}

func (x *PrepareMsgSig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ReplyMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	To             string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From           string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	ClientMsg      *ClientMsg             `protobuf:"bytes,3,opt,name=client_msg,json=clientMsg,proto3" json:"client_msg,omitempty"`
	Success        bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ExecutedSeqNum int64                  `protobuf:"varint,6,opt,name=executed_seq_num,json=executedSeqNum,proto3" json:"executed_seq_num,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	mi := &file_pbft_transport_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{14}
}

func (x *ReplyMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ReplyMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ReplyMessage) GetClientMsg() *ClientMsg {
	if x != nil {
		return x.ClientMsg
	}
	return nil
}

func (x *ReplyMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplyMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReplyMessage) GetExecutedSeqNum() int64 {
	if x != nil {
		return x.ExecutedSeqNum
	}
	return 0
}

type CommitTps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	ClientMsg     *ClientMsgReply        `protobuf:"bytes,3,opt,name=client_msg,json=clientMsg,proto3" json:"client_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTps) Reset() {
	*x = CommitTps{}
	mi := &file_pbft_transport_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTps) ProtoMessage() {}

func (x *CommitTps) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTps.ProtoReflect.Descriptor instead.
func (*CommitTps) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{15}
}

func (x *CommitTps) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *CommitTps) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CommitTps) GetClientMsg() *ClientMsgReply {
	if x != nil {
		return x.ClientMsg
	}
	return nil
}

type LeaderIdUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	NewLeaderId   int32                  `protobuf:"varint,3,opt,name=new_leader_id,json=newLeaderId,proto3" json:"new_leader_id,omitempty"`
	View          int64                  `protobuf:"varint,4,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderIdUpdate) Reset() {
	*x = LeaderIdUpdate{}
	mi := &file_pbft_transport_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderIdUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderIdUpdate) ProtoMessage() {}

func (x *LeaderIdUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderIdUpdate.ProtoReflect.Descriptor instead.
func (*LeaderIdUpdate) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{16}
}

func (x *LeaderIdUpdate) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *LeaderIdUpdate) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *LeaderIdUpdate) GetNewLeaderId() int32 {
	if x != nil {
		return x.NewLeaderId
	}
	return 0
}

func (x *LeaderIdUpdate) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

type CloseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseMessage) Reset() {
	*x = CloseMessage{}
	mi := &file_pbft_transport_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseMessage) ProtoMessage() {}

func (x *CloseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseMessage.ProtoReflect.Descriptor instead.
func (*CloseMessage) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{17}
}

func (x *CloseMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CloseMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CloseMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MsgType   string                 `protobuf:"bytes,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	From      int32                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	Signature []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Request
	//	*Envelope_Preprepare
	//	*Envelope_Prepare
	//	*Envelope_Commit
	//	*Envelope_Reply
	//	*Envelope_Close
	//	*Envelope_CommitTps
	//	*Envelope_LeaderIdUpdate
	//	*Envelope_VcRunningStatus
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_pbft_transport_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{18}
}

func (x *Envelope) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *Envelope) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetRequest() *RequestMessage {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Envelope) GetPreprepare() *PreprepareMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Preprepare); ok {
			return x.Preprepare
		}
	}
	return nil
}

func (x *Envelope) GetPrepare() *PrepareMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Prepare); ok {
			return x.Prepare
		}
	}
	return nil
}

func (x *Envelope) GetCommit() *CommitMsg {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *Envelope) GetReply() *ReplyMessage {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Reply); ok {
			return x.Reply
		}
	}
	return nil
}

func (x *Envelope) GetClose() *CloseMessage {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *Envelope) GetCommitTps() *CommitTps {
	if x != nil {
		if x, ok := x.Body.(*Envelope_CommitTps); ok {
			return x.CommitTps
		}
	}
	return nil
}

func (x *Envelope) GetLeaderIdUpdate() *LeaderIdUpdate {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LeaderIdUpdate); ok {
			return x.LeaderIdUpdate
		}
	}
	return nil
}

func (x *Envelope) GetVcRunningStatus() *VCRunningStatus {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VcRunningStatus); ok {
			return x.VcRunningStatus
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Request struct {
	Request *RequestMessage `protobuf:"bytes,10,opt,name=request,proto3,oneof"`
}

type Envelope_Preprepare struct {
	Preprepare *PreprepareMsg `protobuf:"bytes,11,opt,name=preprepare,proto3,oneof"`
}

type Envelope_Prepare struct {
	Prepare *PrepareMsg `protobuf:"bytes,12,opt,name=prepare,proto3,oneof"`
}

type Envelope_Commit struct {
	Commit *CommitMsg `protobuf:"bytes,13,opt,name=commit,proto3,oneof"`
}

type Envelope_Reply struct {
	Reply *ReplyMessage `protobuf:"bytes,14,opt,name=reply,proto3,oneof"`
}

type Envelope_Close struct {
	Close *CloseMessage `protobuf:"bytes,15,opt,name=close,proto3,oneof"`
}

type Envelope_CommitTps struct {
	CommitTps *CommitTps `protobuf:"bytes,20,opt,name=commit_tps,json=commitTps,proto3,oneof"`
}

type Envelope_LeaderIdUpdate struct {
	LeaderIdUpdate *LeaderIdUpdate `protobuf:"bytes,21,opt,name=leader_id_update,json=leaderIdUpdate,proto3,oneof"`
}

type Envelope_VcRunningStatus struct {
	VcRunningStatus *VCRunningStatus `protobuf:"bytes,22,opt,name=vc_running_status,json=vcRunningStatus,proto3,oneof"`
}

func (*Envelope_Request) isEnvelope_Body() {}

func (*Envelope_Preprepare) isEnvelope_Body() {}

func (*Envelope_Prepare) isEnvelope_Body() {}

func (*Envelope_Commit) isEnvelope_Body() {}

func (*Envelope_Reply) isEnvelope_Body() {}

func (*Envelope_Close) isEnvelope_Body() {}

func (*Envelope_CommitTps) isEnvelope_Body() {}

func (*Envelope_LeaderIdUpdate) isEnvelope_Body() {}

func (*Envelope_VcRunningStatus) isEnvelope_Body() {}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pbft_transport_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pbft_transport_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pbft_transport_proto_rawDescGZIP(), []int{19}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pbft_transport_proto protoreflect.FileDescriptor

const file_pbft_transport_proto_rawDesc = "" +
	"\n" +
	"\x14pbft_transport.proto\x12\x11pbft.transport.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n" +
	"\vTransaction\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"\xc2\x01\n" +
	"\tClientMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x120\n" +
	"\x03txn\x18\x03 \x01(\v2\x1e.pbft.transport.v1.TransactionR\x03txn\x12\x1f\n" +
	"\vclient_name\x18\x04 \x01(\tR\n" +
	"clientName\x12\x18\n" +
	"\apadding\x18\x05 \x01(\tR\apadding\"\xad\x01\n" +
	"\x0eClientMsgReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x120\n" +
	"\x03txn\x18\x03 \x01(\v2\x1e.pbft.transport.v1.TransactionR\x03txn\x12\x1f\n" +
	"\vclient_name\x18\x04 \x01(\tR\n" +
	"clientName\"d\n" +
	"\x12ClientMsgSignature\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.pbft.transport.v1.ClientMsgR\x04data\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"d\n" +
	"\x0eRequestMessage\x127\n" +
	"\x03txs\x18\x01 \x03(\v2%.pbft.transport.v1.ClientMsgSignatureR\x03txs\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\tR\amsgType\"Y\n" +
	"\x18ClientBatchDigestPayload\x12=\n" +
	"\vclient_msgs\x18\x01 \x03(\v2\x1c.pbft.transport.v1.ClientMsgR\n" +
	"clientMsgs\"i\n" +
	"\x0fVCRunningStatus\x127\n" +
	"\x03txs\x18\x01 \x03(\v2%.pbft.transport.v1.ClientMsgSignatureR\x03txs\x12\x1d\n" +
	"\n" +
	"vc_running\x18\x02 \x01(\bR\tvcRunning\"\xf7\x01\n" +
	"\rPreprepareMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12D\n" +
	"\n" +
	"client_msg\x18\x03 \x03(\v2%.pbft.transport.v1.ClientMsgSignatureR\tclientMsg\x12*\n" +
	"\x11digest_client_msg\x18\x05 \x01(\fR\x0fdigestClientMsg\x12A\n" +
	"\x1ddigest_individual_client_msgs\x18\x06 \x03(\fR\x1adigestIndividualClientMsgsJ\x04\b\x04\x10\x05\"v\n" +
	"\x15PreprepareSignPayload\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12*\n" +
	"\x11digest_client_msg\x18\x03 \x01(\fR\x0fdigestClientMsgJ\x04\b\x04\x10\x05\"k\n" +
	"\n" +
	"PrepareMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x12\n" +
	"\x04from\x18\x04 \x01(\x05R\x04fromJ\x04\b\x05\x10\x06\"j\n" +
	"\tCommitMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x12\n" +
	"\x04from\x18\x04 \x01(\x05R\x04fromJ\x04\b\x05\x10\x06\"\xaf\x01\n" +
	"\x11PreprepareMsgMini\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12*\n" +
	"\x11digest_client_msg\x18\x03 \x01(\fR\x0fdigestClientMsg\x12A\n" +
	"\x1ddigest_individual_client_msgs\x18\x04 \x03(\fR\x1adigestIndividualClientMsgs\"\xcc\x01\n" +
	"\x10PreprepareMsgSig\x12T\n" +
	"\x13preprepare_msg_mini\x18\x01 \x01(\v2$.pbft.transport.v1.PreprepareMsgMiniR\x11preprepareMsgMini\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12D\n" +
	"\n" +
	"actual_msg\x18\x03 \x01(\v2%.pbft.transport.v1.ClientMsgSignatureR\tactualMsg\"m\n" +
	"\rPrepareMsgSig\x12>\n" +
	"\vprepare_msg\x18\x01 \x01(\v2\x1d.pbft.transport.v1.PrepareMsgR\n" +
	"prepareMsg\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xc9\x01\n" +
	"\fReplyMessage\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12;\n" +
	"\n" +
	"client_msg\x18\x03 \x01(\v2\x1c.pbft.transport.v1.ClientMsgR\tclientMsg\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12(\n" +
	"\x10executed_seq_num\x18\x06 \x01(\x03R\x0eexecutedSeqNum\"q\n" +
	"\tCommitTps\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12@\n" +
	"\n" +
	"client_msg\x18\x03 \x01(\v2!.pbft.transport.v1.ClientMsgReplyR\tclientMsg\"l\n" +
	"\x0eLeaderIdUpdate\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\"\n" +
	"\rnew_leader_id\x18\x03 \x01(\x05R\vnewLeaderId\x12\x12\n" +
	"\x04view\x18\x04 \x01(\x03R\x04view\"P\n" +
	"\fCloseMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"\xa7\x05\n" +
	"\bEnvelope\x12\x19\n" +
	"\bmsg_type\x18\x01 \x01(\tR\amsgType\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x05R\x04from\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12=\n" +
	"\arequest\x18\n" +
	" \x01(\v2!.pbft.transport.v1.RequestMessageH\x00R\arequest\x12B\n" +
	"\n" +
	"preprepare\x18\v \x01(\v2 .pbft.transport.v1.PreprepareMsgH\x00R\n" +
	"preprepare\x129\n" +
	"\aprepare\x18\f \x01(\v2\x1d.pbft.transport.v1.PrepareMsgH\x00R\aprepare\x126\n" +
	"\x06commit\x18\r \x01(\v2\x1c.pbft.transport.v1.CommitMsgH\x00R\x06commit\x127\n" +
	"\x05reply\x18\x0e \x01(\v2\x1f.pbft.transport.v1.ReplyMessageH\x00R\x05reply\x127\n" +
	"\x05close\x18\x0f \x01(\v2\x1f.pbft.transport.v1.CloseMessageH\x00R\x05close\x12=\n" +
	"\n" +
	"commit_tps\x18\x14 \x01(\v2\x1c.pbft.transport.v1.CommitTpsH\x00R\tcommitTps\x12M\n" +
	"\x10leader_id_update\x18\x15 \x01(\v2!.pbft.transport.v1.LeaderIdUpdateH\x00R\x0eleaderIdUpdate\x12P\n" +
	"\x11vc_running_status\x18\x16 \x01(\v2\".pbft.transport.v1.VCRunningStatusH\x00R\x0fvcRunningStatusB\x06\n" +
	"\x04body\"+\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xa2\x01\n" +
	"\rPBFTTransport\x12>\n" +
	"\aDeliver\x12\x1b.pbft.transport.v1.Envelope\x1a\x16.pbft.transport.v1.Ack\x12Q\n" +
	"\x11ClientNodeChannel\x12\x1b.pbft.transport.v1.Envelope\x1a\x1b.pbft.transport.v1.Envelope(\x010\x01B7Z5github.com/michael112233/pbft/transportpb;transportpbb\x06proto3"

var (
	file_pbft_transport_proto_rawDescOnce sync.Once
	file_pbft_transport_proto_rawDescData []byte
)

func file_pbft_transport_proto_rawDescGZIP() []byte {
	file_pbft_transport_proto_rawDescOnce.Do(func() {
		file_pbft_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbft_transport_proto_rawDesc), len(file_pbft_transport_proto_rawDesc)))
	})
	return file_pbft_transport_proto_rawDescData
}

var file_pbft_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pbft_transport_proto_goTypes = []any{
	(*Transaction)(nil),              // 0: pbft.transport.v1.Transaction
	(*ClientMsg)(nil),                // 1: pbft.transport.v1.ClientMsg
	(*ClientMsgReply)(nil),           // 2: pbft.transport.v1.ClientMsgReply
	(*ClientMsgSignature)(nil),       // 3: pbft.transport.v1.ClientMsgSignature
	(*RequestMessage)(nil),           // 4: pbft.transport.v1.RequestMessage
	(*ClientBatchDigestPayload)(nil), // 5: pbft.transport.v1.ClientBatchDigestPayload
	(*VCRunningStatus)(nil),          // 6: pbft.transport.v1.VCRunningStatus
	(*PreprepareMsg)(nil),            // 7: pbft.transport.v1.PreprepareMsg
	(*PreprepareSignPayload)(nil),    // 8: pbft.transport.v1.PreprepareSignPayload
	(*PrepareMsg)(nil),               // 9: pbft.transport.v1.PrepareMsg
	(*CommitMsg)(nil),                // 10: pbft.transport.v1.CommitMsg
	(*PreprepareMsgMini)(nil),        // 11: pbft.transport.v1.PreprepareMsgMini
	(*PreprepareMsgSig)(nil),         // 12: pbft.transport.v1.PreprepareMsgSig
	(*PrepareMsgSig)(nil),            // 13: pbft.transport.v1.PrepareMsgSig
	(*ReplyMessage)(nil),             // 14: pbft.transport.v1.ReplyMessage
	(*CommitTps)(nil),                // 15: pbft.transport.v1.CommitTps
	(*LeaderIdUpdate)(nil),           // 16: pbft.transport.v1.LeaderIdUpdate
	(*CloseMessage)(nil),             // 17: pbft.transport.v1.CloseMessage
	(*Envelope)(nil),                 // 18: pbft.transport.v1.Envelope
	(*Ack)(nil),                      // 19: pbft.transport.v1.Ack
	(*timestamppb.Timestamp)(nil),    // 20: google.protobuf.Timestamp
}
var file_pbft_transport_proto_depIdxs = []int32{
	20, // 0: pbft.transport.v1.ClientMsg.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: pbft.transport.v1.ClientMsg.txn:type_name -> pbft.transport.v1.Transaction
	20, // 2: pbft.transport.v1.ClientMsgReply.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 3: pbft.transport.v1.ClientMsgReply.txn:type_name -> pbft.transport.v1.Transaction
	1,  // 4: pbft.transport.v1.ClientMsgSignature.data:type_name -> pbft.transport.v1.ClientMsg
	3,  // 5: pbft.transport.v1.RequestMessage.txs:type_name -> pbft.transport.v1.ClientMsgSignature
	1,  // 6: pbft.transport.v1.ClientBatchDigestPayload.client_msgs:type_name -> pbft.transport.v1.ClientMsg
	3,  // 7: pbft.transport.v1.VCRunningStatus.txs:type_name -> pbft.transport.v1.ClientMsgSignature
	3,  // 8: pbft.transport.v1.PreprepareMsg.client_msg:type_name -> pbft.transport.v1.ClientMsgSignature
	11, // 9: pbft.transport.v1.PreprepareMsgSig.preprepare_msg_mini:type_name -> pbft.transport.v1.PreprepareMsgMini
	3,  // 10: pbft.transport.v1.PreprepareMsgSig.actual_msg:type_name -> pbft.transport.v1.ClientMsgSignature
	9,  // 11: pbft.transport.v1.PrepareMsgSig.prepare_msg:type_name -> pbft.transport.v1.PrepareMsg
	1,  // 12: pbft.transport.v1.ReplyMessage.client_msg:type_name -> pbft.transport.v1.ClientMsg
	2,  // 13: pbft.transport.v1.CommitTps.client_msg:type_name -> pbft.transport.v1.ClientMsgReply
	4,  // 14: pbft.transport.v1.Envelope.request:type_name -> pbft.transport.v1.RequestMessage
	7,  // 15: pbft.transport.v1.Envelope.preprepare:type_name -> pbft.transport.v1.PreprepareMsg
	9,  // 16: pbft.transport.v1.Envelope.prepare:type_name -> pbft.transport.v1.PrepareMsg
	10, // 17: pbft.transport.v1.Envelope.commit:type_name -> pbft.transport.v1.CommitMsg
	14, // 18: pbft.transport.v1.Envelope.reply:type_name -> pbft.transport.v1.ReplyMessage
	17, // 19: pbft.transport.v1.Envelope.close:type_name -> pbft.transport.v1.CloseMessage
	15, // 20: pbft.transport.v1.Envelope.commit_tps:type_name -> pbft.transport.v1.CommitTps
	16, // 21: pbft.transport.v1.Envelope.leader_id_update:type_name -> pbft.transport.v1.LeaderIdUpdate
	6,  // 22: pbft.transport.v1.Envelope.vc_running_status:type_name -> pbft.transport.v1.VCRunningStatus
	18, // 23: pbft.transport.v1.PBFTTransport.Deliver:input_type -> pbft.transport.v1.Envelope
	18, // 24: pbft.transport.v1.PBFTTransport.ClientNodeChannel:input_type -> pbft.transport.v1.Envelope
	19, // 25: pbft.transport.v1.PBFTTransport.Deliver:output_type -> pbft.transport.v1.Ack
	18, // 26: pbft.transport.v1.PBFTTransport.ClientNodeChannel:output_type -> pbft.transport.v1.Envelope
	25, // [25:27] is the sub-list for method output_type
	23, // [23:25] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_pbft_transport_proto_init() }
func file_pbft_transport_proto_init() {
	if File_pbft_transport_proto != nil {
		return
	}
	file_pbft_transport_proto_msgTypes[18].OneofWrappers = []any{
		(*Envelope_Request)(nil),
		(*Envelope_Preprepare)(nil),
		(*Envelope_Prepare)(nil),
		(*Envelope_Commit)(nil),
		(*Envelope_Reply)(nil),
		(*Envelope_Close)(nil),
		(*Envelope_CommitTps)(nil),
		(*Envelope_LeaderIdUpdate)(nil),
		(*Envelope_VcRunningStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbft_transport_proto_rawDesc), len(file_pbft_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pbft_transport_proto_goTypes,
		DependencyIndexes: file_pbft_transport_proto_depIdxs,
		MessageInfos:      file_pbft_transport_proto_msgTypes,
	}.Build()
	File_pbft_transport_proto = out.File
	file_pbft_transport_proto_goTypes = nil
	file_pbft_transport_proto_depIdxs = nil
}
