// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/pbft_transport.proto

package transportpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PBFTTransport_Deliver_FullMethodName           = "/pbft.transport.v1.PBFTTransport/Deliver"
	PBFTTransport_ClientNodeChannel_FullMethodName = "/pbft.transport.v1.PBFTTransport/ClientNodeChannel"
)

// PBFTTransportClient is the client API for PBFTTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PBFTTransportClient interface {
	Deliver(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Ack, error)
	ClientNodeChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error)
}

type pBFTTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewPBFTTransportClient(cc grpc.ClientConnInterface) PBFTTransportClient {
	return &pBFTTransportClient{cc}
}

func (c *pBFTTransportClient) Deliver(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, PBFTTransport_Deliver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTTransportClient) ClientNodeChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PBFTTransport_ServiceDesc.Streams[0], PBFTTransport_ClientNodeChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Envelope, Envelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PBFTTransport_ClientNodeChannelClient = grpc.BidiStreamingClient[Envelope, Envelope]

// PBFTTransportServer is the server API for PBFTTransport service.
// All implementations must embed UnimplementedPBFTTransportServer
// for forward compatibility.
type PBFTTransportServer interface {
	Deliver(context.Context, *Envelope) (*Ack, error)
	ClientNodeChannel(grpc.BidiStreamingServer[Envelope, Envelope]) error
	mustEmbedUnimplementedPBFTTransportServer()
}

// UnimplementedPBFTTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPBFTTransportServer struct{}

func (UnimplementedPBFTTransportServer) Deliver(context.Context, *Envelope) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedPBFTTransportServer) ClientNodeChannel(grpc.BidiStreamingServer[Envelope, Envelope]) error {
	return status.Error(codes.Unimplemented, "method ClientNodeChannel not implemented")
}
func (UnimplementedPBFTTransportServer) mustEmbedUnimplementedPBFTTransportServer() {}
func (UnimplementedPBFTTransportServer) testEmbeddedByValue()                       {}

// UnsafePBFTTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PBFTTransportServer will
// result in compilation errors.
type UnsafePBFTTransportServer interface {
	mustEmbedUnimplementedPBFTTransportServer()
}

func RegisterPBFTTransportServer(s grpc.ServiceRegistrar, srv PBFTTransportServer) {
	// If the following call panics, it indicates UnimplementedPBFTTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PBFTTransport_ServiceDesc, srv)
}

func _PBFTTransport_Deliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Envelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTTransportServer).Deliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTTransport_Deliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTTransportServer).Deliver(ctx, req.(*Envelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTTransport_ClientNodeChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PBFTTransportServer).ClientNodeChannel(&grpc.GenericServerStream[Envelope, Envelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PBFTTransport_ClientNodeChannelServer = grpc.BidiStreamingServer[Envelope, Envelope]

// PBFTTransport_ServiceDesc is the grpc.ServiceDesc for PBFTTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PBFTTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbft.transport.v1.PBFTTransport",
	HandlerType: (*PBFTTransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deliver",
			Handler:    _PBFTTransport_Deliver_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientNodeChannel",
			Handler:       _PBFTTransport_ClientNodeChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/pbft_transport.proto",
}
