#!/usr/bin/env python3
"""
Python script to plot TPS and Latency vs Time from CSV data generated by the PBFT system.
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import sys

def plot_tps_data(csv_file='parallel_logs/port_25610_client/tps_results.csv', tps_output='tps_plot.png', latency_output='latency_plot.png'):
    """
    Read CSV data and create line plots of TPS and Latency vs Time.
    
    Args:
        csv_file (str): Path to the CSV file containing TPS, Time, and Latency data
        tps_output (str): Path for the TPS plot output image
        latency_output (str): Path for the Latency plot output image
    """
    
    # Check if CSV file exists
    if not os.path.exists(csv_file):
        print(f"Error: CSV file '{csv_file}' not found!")
        print("Please run the PBFT system first to generate the CSV data.")
        return False
    
    try:
        # Read CSV data
        df = pd.read_csv(csv_file)
        
        # Check if required columns exist
        required_columns = ['Time', 'TPS', 'Latency']
        missing_columns = [col for col in required_columns if col not in df.columns]
        if missing_columns:
            print(f"Error: CSV file missing required columns: {missing_columns}")
            print(f"Found columns: {list(df.columns)}")
            return False
        
        # Remove rows with empty values
        df = df.dropna()
        
        if len(df) == 0:
            print("Error: No valid data found in CSV file!")
            return False
        
        # Create TPS plot
        plt.figure(figsize=(12, 8))
        plt.plot(df['Time'], df['TPS'], 'b-', linewidth=2, marker='o', markersize=4)
        
        # Customize TPS plot
        plt.title('PBFT System Performance: TPS vs Time', fontsize=16, fontweight='bold')
        plt.xlabel('Time (seconds)', fontsize=14)
        plt.ylabel('Transactions Per Second (TPS)', fontsize=14)
        plt.grid(True, alpha=0.3)
        
        # Add TPS statistics
        max_tps = df['TPS'].max()
        avg_tps = df['TPS'].mean()
        total_time = df['Time'].max()
        
        # Add text box with TPS statistics
        tps_stats_text = f'Max TPS: {max_tps:.2f}\nAvg TPS: {avg_tps:.2f}\nTotal Time: {total_time:.2f}s'
        plt.text(0.02, 0.98, tps_stats_text, transform=plt.gca().transAxes, 
                verticalalignment='top', bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.8))
        
        # Improve layout
        plt.tight_layout()
        
        # Save TPS plot
        plt.savefig(tps_output, dpi=300, bbox_inches='tight')
        print(f"TPS plot saved as: {tps_output}")
        
        # Show TPS plot
        plt.show()
        
        # Create Latency plot
        plt.figure(figsize=(12, 8))
        plt.plot(df['Time'], df['Latency'], 'r-', linewidth=2, marker='s', markersize=4)
        
        # Customize Latency plot
        plt.title('PBFT System Performance: Latency vs Time', fontsize=16, fontweight='bold')
        plt.xlabel('Time (seconds)', fontsize=14)
        plt.ylabel('Latency (milliseconds)', fontsize=14)
        plt.grid(True, alpha=0.3)
        
        # Add Latency statistics
        max_latency = df['Latency'].max()
        avg_latency = df['Latency'].mean()
        min_latency = df['Latency'].min()
        
        # Add text box with Latency statistics
        latency_stats_text = f'Max Latency: {max_latency:.4f}ms\nAvg Latency: {avg_latency:.4f}ms\nMin Latency: {min_latency:.4f}ms'
        plt.text(0.02, 0.98, latency_stats_text, transform=plt.gca().transAxes, 
                verticalalignment='top', bbox=dict(boxstyle='round', facecolor='lightcoral', alpha=0.8))
        
        # Improve layout
        plt.tight_layout()
        
        # Save Latency plot
        plt.savefig(latency_output, dpi=300, bbox_inches='tight')
        print(f"Latency plot saved as: {latency_output}")
        
        # Show Latency plot
        plt.show()
        
        # Print summary statistics
        print(f"\nSummary Statistics:")
        print(f"Total data points: {len(df)}")
        print(f"Time range: {df['Time'].min():.2f}s - {df['Time'].max():.2f}s")
        print(f"TPS range: {df['TPS'].min():.2f} - {df['TPS'].max():.2f}")
        print(f"Latency range: {df['Latency'].min():.4f}ms - {df['Latency'].max():.4f}ms")
        print(f"Average TPS: {avg_tps:.2f}")
        print(f"Maximum TPS: {max_tps:.2f}")
        print(f"Average Latency: {avg_latency:.4f}ms")
        print(f"Maximum Latency: {max_latency:.4f}ms")
        
        return True
        
    except Exception as e:
        print(f"Error processing CSV file: {e}")
        return False

def main():
    """Main function to handle command line arguments and run the plotting."""
    
    # Default values
    # csv_file = 'parallel_logs/port_26010_client/tps_results.csv'
    csv_file = 'tps_results.csv'
    tps_output = 'tps_plot.png'
    latency_output = 'latency_plot.png'
    
    # Parse command line arguments
    if len(sys.argv) > 1:
        csv_file = sys.argv[1]
    if len(sys.argv) > 2:
        tps_output = sys.argv[2]
    if len(sys.argv) > 3:
        latency_output = sys.argv[3]
    
    print(f"Reading data from: {csv_file}")
    print(f"TPS plot will be saved as: {tps_output}")
    print(f"Latency plot will be saved as: {latency_output}")
    
    # Create the plots
    success = plot_tps_data(csv_file, tps_output, latency_output)
    
    if success:
        print("Plotting completed successfully!")
    else:
        print("Plotting failed!")
        sys.exit(1)

if __name__ == "__main__":
    main()